// Autogenerated file

#ifndef BALL_H__
#define BALL_H__

#include <stdint.h>

#define BALL_BITMAP_WIDTH   32
#define BALL_BITMAP_HEIGHT  32
#define BALL_NUM_IMAGES     5

#define BALL_ball0_png 0
#define BALL_ball1_png 1
#define BALL_ball2_png 2
#define BALL_ball3_png 3
#define BALL_shadow_png 4

extern const uint16_t BALL_texcoords[];

#endif // BALL_H__
