// Autogenerated file

#include <stdint.h>

const uint16_t BALL_texcoords[] = {
    16, 0, 4, 4, // ball0.png
    12, 0, 4, 4, // ball1.png
    8, 0, 4, 4, // ball2.png
    4, 0, 4, 4, // ball3.png
    0, 0, 4, 4, // shadow.png
};