// Autogenerated file

#include <stdint.h>

const uint16_t CORNERFLAG_texcoords[] = {
    16, 12, 16, 12, // spr0000.png
    16, 0, 16, 12, // spr0001.png
    0, 12, 16, 12, // spr0002.png
    0, 0, 16, 12, // spr0003.png
};