// Autogenerated file

#ifndef CORNERFLAG_H__
#define CORNERFLAG_H__

#include <stdint.h>

#define CORNERFLAG_BITMAP_WIDTH   64
#define CORNERFLAG_BITMAP_HEIGHT  32
#define CORNERFLAG_NUM_IMAGES     4

#define CORNERFLAG_spr0000_png 0
#define CORNERFLAG_spr0001_png 1
#define CORNERFLAG_spr0002_png 2
#define CORNERFLAG_spr0003_png 3

extern const uint16_t CORNERFLAG_texcoords[];

#endif // CORNERFLAG_H__
