// Autogenerated file

#ifndef GOAL_H__
#define GOAL_H__

#include <stdint.h>

#define GOAL_BITMAP_WIDTH   128
#define GOAL_BITMAP_HEIGHT  64
#define GOAL_NUM_IMAGES     2

#define GOAL_spr0000_png 0
#define GOAL_spr0001_png 1

extern const uint16_t GOAL_texcoords[];

#endif // GOAL_H__
