// Autogenerated by tools/extract_player_frames.py -- do not edit.
#pragma once

#include <stdint.h>

#define PLAYER_FRAME_COUNT 101

extern const int8_t PLAYER_FRAME_CENTER_X[PLAYER_FRAME_COUNT];
extern const int8_t PLAYER_FRAME_CENTER_Y[PLAYER_FRAME_COUNT];
