// Autogenerated file

#include <stdint.h>

const uint16_t REFEREE_texcoords[] = {
    25, 0, 12, 15, // spr0000.png
    12, 0, 13, 15, // spr0001.png
    48, 0, 11, 15, // spr0002.png
    22, 15, 12, 15, // spr0003.png
    45, 15, 11, 15, // spr0004.png
    9, 16, 13, 15, // spr0005.png
    56, 15, 9, 15, // spr0006.png
    0, 16, 9, 16, // spr0007.png
    0, 0, 12, 16, // spr0008.png
    37, 0, 11, 15, // spr0009.png
    34, 15, 11, 15, // spr0010.png
};