// Autogenerated file

#ifndef REFEREE_H__
#define REFEREE_H__

#include <stdint.h>

#define REFEREE_BITMAP_WIDTH   128
#define REFEREE_BITMAP_HEIGHT  32
#define REFEREE_NUM_IMAGES     11

#define REFEREE_spr0000_png 0
#define REFEREE_spr0001_png 1
#define REFEREE_spr0002_png 2
#define REFEREE_spr0003_png 3
#define REFEREE_spr0004_png 4
#define REFEREE_spr0005_png 5
#define REFEREE_spr0006_png 6
#define REFEREE_spr0007_png 7
#define REFEREE_spr0008_png 8
#define REFEREE_spr0009_png 9
#define REFEREE_spr0010_png 10

extern const uint16_t REFEREE_texcoords[];

#endif // REFEREE_H__
