// Auto-generated by tools/convert_addr.py -- DO NOT EDIT BY HAND.
// Source: D:/Programowanie/SWOS_DS/openswos/game/scripts/SwosVm/Memory.cs (OpenSWOS SwosVm.Memory.Addr).
// Regenerate with: python tools/convert_addr.py <Memory.cs> include/swos_addr.h
#pragma once

#define ADDR_DataBase                           (0x010000)
#define ADDR_kBallKickingSpeed                  (0x010000)  // 2208
#define ADDR_kHighKickBallSpeed                 (0x010002)  // 2688
#define ADDR_kNormalKickBallSpeed               (0x010004)  // 2560
#define ADDR_kPlayerTacklingSpeed               (0x010006)  // 1792
#define ADDR_kJumpHeaderSpeed                   (0x010008)  // 2048
#define ADDR_kGoalkeeperCatchSpeed              (0x01000A)  // 768
#define ADDR_kGoalkeeperMoveToBallSpeed         (0x01000C)  // 1024
#define ADDR_kGoalkeeperSpeedWhenGameStopped    (0x01000E)  // 1024
#define ADDR_kSubstitutedPlayerSpeed            (0x010010)  // 1536
#define ADDR_kRefereeSpeed                      (0x010012)  // 1024
#define ADDR_kBallKickingDeltaZ                 (0x010014)  // 0x14000
#define ADDR_kBallJumpHeaderDeltaZ              (0x010018)  // 0xA000
#define ADDR_kBallGroundConstant                (0x01001C)  // word — PC=13 / Amiga=16
#define ADDR_kBallAirConstant                   (0x01001E)  // word — PC=4  / Amiga=10
#define ADDR_kGravityConstant                   (0x010020)  // dword — PC=3291 / Amiga=4608
#define ADDR_kKeeperSaveDistance                (0x010024)  // word — PC=16 / Amiga=24
#define ADDR_ballSpeedBounceFactor              (0x010028)
#define ADDR_ballBounceFactor                   (0x01002A)
#define ADDR_pitchBallSpeedFactor               (0x01002C)
#define ADDR_kGoalkeeperDiveDeltasBase          (0x010040)
#define ADDR_kBallPlOffsetsBase                 (0x010080)
#define ADDR_kHighKickDeltaZ                    (0x0100A0)  // dword 0x20000 (Q16.16)
#define ADDR_kNormalKickDeltaZ                  (0x0100A4)  // dword 0x16000 (Q16.16)
#define ADDR_kSpinMultiplierFactor              (0x0100B0)  // 20 bytes
#define ADDR_kKickSpinFactor                    (0x0100D0)  // 64 bytes
#define ADDR_kPassingSpinFactor                 (0x010120)  // 64 bytes
#define ADDR_gameStatePl                        (0x010180)
#define ADDR_gameState                          (0x010182)
#define ADDR_ballNextX                          (0x010184)  // word
#define ADDR_ballNextY                          (0x010186)  // word
#define ADDR_hideBall                           (0x010188)  // word
#define ADDR_ballShadowImageIndex               (0x01018A)  // word
#define ADDR_ballStaticFrameIndices_Addr        (0x01018C)  // dword — pointer
#define ADDR_ballMovingFrameIndices_Addr        (0x010190)  // dword — pointer
#define ADDR_ballStaticFrameIndices_Table       (0x010200)  // bytes
#define ADDR_ballMovingFrameIndices_Table       (0x010210)  // bytes
#define ADDR_g_substituteInProgress             (0x010220)  // word — 0 = no substitution
#define ADDR_teamThatSubstitutes                (0x010224)  // dword — pointer to TeamData of subbing team
#define ADDR_lastTeamPlayedBeforeBreak          (0x010228)  // dword — pointer
#define ADDR_team1NumSubs                       (0x01022C)  // word
#define ADDR_team2NumSubs                       (0x01022E)  // word
#define ADDR_ballNextGroundX                    (0x010230)  // word
#define ADDR_ballNextGroundY                    (0x010232)  // word
#define ADDR_ballNextGroundZDead                (0x010234)  // word
#define ADDR_ballDefensiveY                     (0x010600)  // word
#define ADDR_ballDefensiveZ                     (0x010602)  // word
#define ADDR_ballNotHighX                       (0x010604)  // word
#define ADDR_ballNotHighY                       (0x010606)  // word
#define ADDR_strikeDestX                        (0x010608)  // word
#define ADDR_ballStrikeY                        (0x01060A)  // word
#define ADDR_ballStrikeZ                        (0x01060C)  // word
#define ADDR_team1TotalGoals                    (0x010240)  // word
#define ADDR_team2TotalGoals                    (0x010242)  // word
#define ADDR_team1PenaltyGoals                  (0x010244)  // word
#define ADDR_team2PenaltyGoals                  (0x010246)  // word
#define ADDR_team1GoalsDigit1                   (0x010248)  // word
#define ADDR_team1GoalsDigit2                   (0x01024A)  // word
#define ADDR_statsTeam1Goals                    (0x01024C)  // word
#define ADDR_team2GoalsDigit1                   (0x01024E)  // word
#define ADDR_team2GoalsDigit2                   (0x010250)  // word
#define ADDR_statsTeam2Goals                    (0x010252)  // word
#define ADDR_statsTeam1GoalsCopy                (0x010254)  // word
#define ADDR_statsTeam2GoalsCopy                (0x010256)  // word
#define ADDR_team1GoalsFirstLeg                 (0x010258)  // word
#define ADDR_team2GoalsFirstLeg                 (0x01025A)  // word
#define ADDR_goalScored                         (0x01025C)  // word
#define ADDR_runSlower                          (0x01025E)  // word
#define ADDR_lastTeamScoredNumber               (0x010260)  // word (1 or 2)
#define ADDR_lastPlayerScored                   (0x010264)  // dword — pointer to scorer sprite
#define ADDR_currentScorer                      (0x010268)  // dword — pointer to scorer sprite
#define ADDR_lastTeamScored                     (0x01026C)  // dword — pointer to TeamData
#define ADDR_goalTypeScored                     (0x010270)  // dword — GoalType enum mirror
#define ADDR_penalty                            (0x010274)  // word — non-zero = penalty kick in progress
#define ADDR_playingPenalties                   (0x010276)  // word — penalty shootout flag
#define ADDR_topTeamInGame                      (0x010278)  // dword
#define ADDR_bottomTeamInGame                   (0x01027C)  // dword
#define ADDR_refState                           (0x010280)  // word — RefereeState enum
#define ADDR_whichCard                          (0x010282)  // word — CardHanding enum
#define ADDR_foulXCoordinate                    (0x010284)  // word
#define ADDR_foulYCoordinate                    (0x010286)  // word
#define ADDR_refTimer                           (0x010288)  // word
#define ADDR_bookedPlayer                       (0x01028C)  // dword — pointer to sprite
#define ADDR_lastTeamBooked                     (0x010290)  // dword — pointer to TeamData
#define ADDR_refComingAnimTable                 (0x0102A0)  // 64 bytes
#define ADDR_refWaitingAnimTable                (0x0102E0)  // 64 bytes
#define ADDR_refYellowCardAnimTable             (0x010320)  // 64 bytes
#define ADDR_refRedCardAnimTable                (0x010360)  // 64 bytes
#define ADDR_refSecondYellowAnimTable           (0x0103A0)  // 64 bytes
#define ADDR_lastFrameTicks                     (0x0103E0)  // word
#define ADDR_lastTeamPlayed                     (0x0103E4)  // dword
#define ADDR_gameLengthInGame                   (0x0103E8)  // word
#define ADDR_gt_gameTime                        (0x0103F0)  // 16 bytes (4 × int)
#define ADDR_gt_gameTimeInMinutes               (0x010400)  // dword
#define ADDR_gt_endGameCounter                  (0x010404)  // dword
#define ADDR_gt_timeDelta                       (0x010408)  // dword
#define ADDR_gt_gameSeconds                     (0x01040C)  // dword
#define ADDR_gt_secondsSwitchAccumulator        (0x010410)  // dword
#define ADDR_gt_showTime                        (0x010414)  // word
#define ADDR_extraTimeState                     (0x010418)  // word — 0=disabled, 1=enabled, -1=running
#define ADDR_penaltiesState                     (0x01041A)  // word — same convention
#define ADDR_secondLeg                          (0x01041C)  // word — non-zero = two-leg tie
#define ADDR_playing2ndGame                     (0x01041E)  // word — non-zero = this is leg 2
#define ADDR_stateGoal                          (0x010420)  // word
#define ADDR_winningTeamPtr                     (0x010424)  // dword
#define ADDR_playRefereeWhistle                 (0x010428)  // word
#define ADDR_lastPlayerPlayed                   (0x01042C)  // dword — last outfielder to touch ball
#define ADDR_lastKeeperPlayed                   (0x010430)  // dword — last keeper to touch ball
#define ADDR_statsTeam1GoalsCopy2               (0x010434)  // word
#define ADDR_statsTeam2GoalsCopy2               (0x010436)  // word
#define ADDR_goalCameraMode                     (0x010438)  // word — g_memByte[455982]
#define ADDR_teamNumThatScored                  (0x01043A)  // word — g_memByte[456644] (1 or 2)
#define ADDR_teamScoredDataPtr                  (0x01043C)  // dword — g_memByte[456648]
#define ADDR_teamScoredGamePtr                  (0x010440)  // dword — g_memByte[456652]
#define ADDR_goalCounter                        (0x010444)  // word — g_memByte[455978]
#define ADDR_patternsGoalCounter                (0x010446)  // word — g_memByte[521016]
#define ADDR_breakCameraMode                    (0x010448)  // word
#define ADDR_goalOut                            (0x01044A)  // word
#define ADDR_forceLeftTeam                      (0x01044C)  // word
#define ADDR_cameraXVelocity                    (0x01044E)  // word
#define ADDR_cameraYVelocity                    (0x010450)  // word
#define ADDR_stoppageTimerTotal                 (0x010452)  // word
#define ADDR_stoppageTimerActive                (0x010454)  // word
#define ADDR_cameraDirection                    (0x010456)  // word
#define ADDR_playerTurnFlags                    (0x010458)  // byte
#define ADDR_gameNotInProgressCounterWriteOnly  (0x01045A)  // word
#define ADDR_currentGameTick                    (0x01045C)  // word
#define ADDR_lastPlayerTurnFlags                (0x01045E)  // word
#define ADDR_ballXQuadrantLimits                (0x010460)  // 5 × word = 10 bytes
#define ADDR_ballYQuadrantLimits                (0x01046C)  // 7 × word = 14 bytes
#define ADDR_ballQuadrantIndex                  (0x01047C)  // word
#define ADDR_ballXQuadrantDead                  (0x01047E)  // word
#define ADDR_ballYQuadrantDead                  (0x010480)  // word
#define ADDR_playerXQuadrantOffset              (0x010482)  // word
#define ADDR_playerYQuadrantOffset              (0x010484)  // word
#define ADDR_ballShadowSpriteBase               (0x04F880)  // 64 bytes reserved
#define ADDR_playGame                           (0x010488)  // word
#define ADDR_frameCounter                       (0x01048C)  // dword
#define ADDR_teamSwitchCounter                  (0x010490)  // dword
#define ADDR_fireBlocked                        (0x010494)  // word
#define ADDR_spaceReplayTimer                   (0x010496)  // word
#define ADDR_penaltiesTimer                     (0x010498)  // word — g_memByte[523156]
#define ADDR_inGameCounter                      (0x01049A)  // word — g_memByte[523132]
#define ADDR_stoppageEventTimer                 (0x01049C)  // word — g_memByte[523122]
#define ADDR_gameNotInProgressCounter           (0x01049E)  // word — readable mirror
#define ADDR_lastGameTick                       (0x0104A0)  // word
#define ADDR_loadCrowdChantSampleFlag           (0x0104A2)  // word
#define ADDR_kGoalkeeperNearJumpSpeed           (0x0104A4)  // word — 2048
#define ADDR_kGoalkeeperFarJumpSpeed            (0x0104A6)  // word — 2048
#define ADDR_kGoalkeeperFarJumpSlowerSpeed      (0x0104A8)  // word — 1280
#define ADDR_kGoalkeeperStrongDeflectBallSpeed  (0x0104AA)  // word
#define ADDR_kGoalkeeperMediumDeflectBallSpeed  (0x0104AC)  // word
#define ADDR_kGoalkeeperWeakDeflectBallSpeed    (0x0104AE)  // word
#define ADDR_kGoalkeeperDeflectDeltaZ           (0x0104B0)  // dword
#define ADDR_kKeeperPenaltySaveDistanceFar      (0x0104B4)  // word
#define ADDR_kKeeperPenaltySaveDistanceNear     (0x0104B6)  // word
#define ADDR_ballDefensiveX                     (0x0104B8)  // word
#define ADDR_ballNotHighZ                       (0x0104BA)  // word
#define ADDR_kDefaultDestinations               (0x0104BC)  // 32 bytes
#define ADDR_goalkeeperDiveDeadVar              (0x0104DC)  // word
#define ADDR_nobodysBallTimer                   (0x0104DE)  // word
#define ADDR_prevLastPlayer                     (0x0104E0)  // dword
#define ADDR_prevLastTeamPlayed                 (0x0104E4)  // dword
#define ADDR_ballInUpperPenaltyArea             (0x0104E8)  // word
#define ADDR_ballInLowerPenaltyArea             (0x0104EA)  // word
#define ADDR_ballInGoalkeeperArea               (0x0104EC)  // word
#define ADDR_lastPlayerBeforeGoalkeeper         (0x0104F0)  // dword
#define ADDR_cameraX                            (0x0104F4)  // dword Q16.16
#define ADDR_cameraY                            (0x0104F8)  // dword Q16.16
#define ADDR_leavingBenchMode                   (0x0104FC)  // word
#define ADDR_g_trainingGame                     (0x010500)  // word
#define ADDR_showFansCounter                    (0x010502)  // word
#define ADDR_g_waitForPlayerToGoInTimer         (0x010504)  // word
#define ADDR_statsTimer                         (0x010508)  // signed word
#define ADDR_resultTimer                        (0x01050C)  // signed dword
#define ADDR_dontShowScorers                    (0x010512)  // word
#define ADDR_topTeamPtr                         (0x010514)  // dword
#define ADDR_bottomTeamPtr                      (0x010518)  // dword
#define ADDR_topTeamStatsData                   (0x010520)  // 32 bytes
#define ADDR_bottomTeamStatsData                (0x010540)  // 32 bytes
#define ADDR_res_showResult                     (0x010560)  // word
#define ADDR_res_team1Name                      (0x010564)  // dword
#define ADDR_res_team2Name                      (0x010568)  // dword
#define ADDR_res_team1NameLength                (0x01056C)  // word
#define ADDR_st_showStats                       (0x010570)  // word
#define ADDR_st_showingUserRequestedStats       (0x010572)  // word
#define ADDR_st_isGoalAttempt                   (0x010574)  // word
#define ADDR_cardsDisallowed                    (0x010580)  // word
#define ADDR_playerCardChance                   (0x010582)  // word
#define ADDR_plg_D3_param                       (0x010584)  // word
#define ADDR_team1NumAllowedInjuries            (0x010586)  // word
#define ADDR_team2NumAllowedInjuries            (0x010588)  // word
#define ADDR_lastTackleNearestTeammate          (0x01058C)  // dword
#define ADDR_inGameTeamPlayerOffsets            (0x010590)  // 11 × word = 22 bytes
#define ADDR_dseg_17E3EE                        (0x0105A8)  // 5 bytes
#define ADDR_dseg_17E3F3                        (0x0105AD)  // 5 bytes
#define ADDR_gamePitchTypeOrSeason              (0x0105B4)  // word
#define ADDR_gameSeason                         (0x0105B6)  // word
#define ADDR_gamePitchType                      (0x0105B8)  // signed word
#define ADDR_plg_D0_param                       (0x0105BA)  // word
#define ADDR_AI_counter                         (0x0105C0)  // word
#define ADDR_AI_attackHalf                      (0x0105C2)  // word
#define ADDR_AI_counterWriteOnly                (0x0105C4)  // word
#define ADDR_deadVarAlways0                     (0x0105C6)  // word
#define ADDR_dseg_1309C1                        (0x0105C8)  // dword
#define ADDR_dseg_132804                        (0x0105CE)  // word
#define ADDR_dseg_132806                        (0x0105D0)  // word
#define ADDR_deadThrowInDirectionVar            (0x0105D2)  // word
#define ADDR_disallowedTurnFlagsCounter         (0x0105D4)  // word
#define ADDR_timeVar                            (0x0105D6)  // signed word
#define ADDR_playerHadBall                      (0x0105D8)  // word
#define ADDR_kInjuryLevels                      (0x0105DA)  // 7 bytes
#define ADDR_kInjuryLevelAlreadyInjured         (0x0105E1)  // 7 bytes
#define ADDR_dseg_17E2EC                        (0x0105E8)  // 8 × word = 16 bytes
#define ADDR_kTackleInjuryProbability           (0x0105F8)  // 4 bytes
#define ADDR_kTackleInjuryProbabilityAlreadyInjured (0x0105FC)  // 4 bytes
#define ADDR_ic_pl1FireCounter                  (0x010700)  // dword (signed)
#define ADDR_ic_pl2FireCounter                  (0x010704)  // dword (signed)
#define ADDR_ic_pl1LastFired                    (0x010708)  // byte
#define ADDR_ic_pl2LastFired                    (0x010709)  // byte
#define ADDR_ic_oldPl1Events                    (0x01070C)  // dword (GameControlEvents)
#define ADDR_ic_oldPl2Events                    (0x010710)  // dword
#define ADDR_ic_pl1LastVertical                 (0x010714)  // dword
#define ADDR_ic_pl1LastHorizontal               (0x010718)  // dword
#define ADDR_ic_pl2LastVertical                 (0x01071C)  // dword
#define ADDR_ic_pl2LastHorizontal               (0x010720)  // dword
#define ADDR_ic_pl1Events                       (0x010724)  // dword — raw input from Godot
#define ADDR_ic_pl2Events                       (0x010728)  // dword
#define ADDR_ic_pl1Fire                         (0x01072C)  // word (-1 / 0)
#define ADDR_ic_pl2Fire                         (0x01072E)  // word
#define ADDR_throwInPassOrKick                  (0x010740)  // word
#define ADDR_aboutToThrowInAnimTable            (0x013500)
#define ADDR_throwInPassAnimTable               (0x013600)
#define ADDR_throwInKickAnimTable               (0x013700)
#define ADDR_AI_throwInDirections               (0x010750)  // 6 bytes
#define ADDR_substitutedPlSprite                (0x010756)  // dword — pointer
#define ADDR_playerNormalStandingAnimTable      (0x013100)
#define ADDR_kStaticHeaderPlayerSpeed           (0x010760)  // word — 256
#define ADDR_playerXQuadrantsCoordinates        (0x010764)  // 30 bytes
#define ADDR_playerYQuadrantCoordinates         (0x010784)  // 32 bytes
#define ADDR_m_playerDownHeadingInterval        (0x0107A4)  // word
#define ADDR_m_playerDownTacklingInterval       (0x0107A6)  // word
#define ADDR_g_tacticsTable                     (0x0107A8)  // 76 bytes
#define ADDR_teamTacticsPool                    (0x010800)  // 19 × 370 = 7030 bytes
#define ADDR_kShotAtGoalMinumumSpeed            (0x012380)  // word — 512
#define ADDR_goalScoredChances                  (0x012382)  // 15 bytes
#define ADDR_dseg_1105EF                        (0x012392)  // word — 512
#define ADDR_dseg_110BDB                        (0x012394)  // 8 × word
#define ADDR_dseg_17EECC                        (0x0123A4)  // 60 bytes
#define ADDR_AI_resumePlayTimer                 (0x012400)  // word
#define ADDR_AI_rand                            (0x012402)  // word
#define ADDR_AI_turnDirection                   (0x012404)  // signed word
#define ADDR_AI_maxStoppageTime                 (0x012406)  // word
#define ADDR_AI_randomRotateTable               (0x012410)  // 4 bytes
#define ADDR_AI_leftSpinTable                   (0x012414)  // 6 bytes
#define ADDR_AI_rotateRightTable                (0x01241C)  // 6 bytes
#define ADDR_AI_longKickTable                   (0x012424)  // 6 bytes
#define ADDR_m_clearResultInterval              (0x01242C)  // word
#define ADDR_m_clearResultHalftimeInterval      (0x01242E)  // word
#define ADDR_frameCount                         (0x012430)  // word
#define ADDR_team1Computer                      (0x012434)  // word
#define ADDR_team2Computer                      (0x012436)  // word
#define ADDR_g_inSubstitutesMenu                (0x012438)  // word
#define ADDR_AI_resultTimer                     (0x01243A)  // word
#define ADDR_m_initalKickInterval               (0x01243C)  // word — 825
#define ADDR_initialKickWriteOnlyTicks          (0x01243E)  // word
#define ADDR_halfNumber                         (0x012440)  // word
#define ADDR_teamPlayingUp                      (0x012442)  // word
#define ADDR_teamStarting                       (0x012444)  // word
#define ADDR_savedTeam1Goals                    (0x012446)  // word
#define ADDR_savedTeam2Goals                    (0x012448)  // word
#define ADDR_team1PenaltyShooterIndex           (0x01244A)  // word
#define ADDR_team2PenaltyShooterIndex           (0x01244C)  // word
#define ADDR_team1PenaltyAttempts               (0x01244E)  // word
#define ADDR_team2PenaltyAttempts               (0x012450)  // word
#define ADDR_injuriesForever                    (0x012452)  // word
#define ADDR_sl_enabled                         (0x012454)  // word
#define ADDR_sl_frameIndex                      (0x012456)  // word
#define ADDR_sl_pictureIndex                    (0x012458)  // word
#define ADDR_m_benchY                           (0x01245A)  // word
#define ADDR_m_opponentBenchY                   (0x01245C)  // word
#define ADDR_g_cameraLeavingSubsTimer           (0x01245E)  // word
#define ADDR_cornerFlags                        (0x012460)  // 24 bytes (4 × 6)
#define ADDR_plComingX                          (0x012478)  // word
#define ADDR_plComingY                          (0x01247A)  // word
#define ADDR_penaltyShooterSprite               (0x01247C)  // dword
#define ADDR_curPlayerNumSprites                (0x012480)  // 16 bytes (2 × 8)
#define ADDR_pnd_topTeam                        (0x012490)  // word (0 = bottom)
#define ADDR_pnd_playerOrdinal                  (0x012492)  // signed word (-1 = hidden)
#define ADDR_pnd_visible                        (0x012494)  // word
#define ADDR_pnd_nobodysBallLastFrame           (0x012496)  // word
#define ADDR_kPlayerWithBallOffsets             (0x012500)  // 32 bytes
#define ADDR_kPlAvgTacklingBallControlDiffChance (0x012520)  // 32 bytes
#define ADDR_kBallSpeedDeltaWhenControlled      (0x012540)  // 16 bytes
#define ADDR_dseg_17E276                        (0x012550)  // 16 bytes
#define ADDR_kBallSpeedFinishing                (0x012560)  // 16 bytes
#define ADDR_kBallSpeedKicking                  (0x012570)  // 16 bytes
#define ADDR_kStaticHeaderBallSpeed             (0x012580)  // word
#define ADDR_kPlayerHeaderSpeedIncrease         (0x012582)  // 16 bytes
#define ADDR_kHeaderLowJumpHeight               (0x012594)  // dword
#define ADDR_kHeaderHighJumpHeight              (0x012598)  // dword
#define ADDR_goodPassSampleCommand              (0x01259C)  // word
#define ADDR_goodPassTimer                      (0x01259E)  // word
#define ADDR_playingGoodPassTimer               (0x0125A0)  // word
#define ADDR_kAIFailedPassChance                (0x0125A4)  // 32 bytes
#define ADDR_kPassingSpeedTable                 (0x0125C4)  // 16 bytes
#define ADDR_kPassingSpeedCloserThan2500        (0x0125C4)
#define ADDR_kPassingSpeed_2500_10000           (0x0125C6)
#define ADDR_kPassingSpeed_10000_22500          (0x0125C8)
#define ADDR_kPassingSpeed_22500_40000          (0x0125CA)
#define ADDR_kPassingSpeed_40000_62500          (0x0125CC)
#define ADDR_kPassingSpeed_62500_90000          (0x0125CE)
#define ADDR_kPassingSpeed_90000_122500         (0x0125D0)
#define ADDR_kPassingSpeedFurtherThan122500     (0x0125D2)
#define ADDR_kBallSpeedPassingIncrease          (0x0125D4)  // 16 bytes
#define ADDR_kFreePassReleasingBallSpeed        (0x0125E4)  // word
#define ADDR_kPlayerTacklingDownTime            (0x0125E6)  // 16 bytes
#define ADDR_kComputerTacklingDownTime          (0x0125F6)  // 16 bytes
#define ADDR_kLeftThrowInBallDestDelta          (0x012606)  // 32 bytes
#define ADDR_kRightThrowInBallDestDelta         (0x012626)  // 32 bytes
#define ADDR_kPenaltyBallDestDelta              (0x012646)  // 32 bytes
#define ADDR_kUpperLeftCornerBallDestDelta      (0x012666)  // 32 bytes
#define ADDR_kUpperRightCornerBallDestDelta     (0x012686)  // 32 bytes
#define ADDR_kLowerLeftCornerBallDestDelta      (0x0126A6)  // 32 bytes
#define ADDR_kLowerRightCornerBallDestDelta     (0x0126C6)  // 32 bytes
#define ADDR_team1InGameTeamHeader              (0x012700)  // 1024 bytes
#define ADDR_team1InGameTeamPlayers             (0x01272A)  // players[0]
#define ADDR_team2InGameTeamHeader              (0x012B00)  // 1024 bytes
#define ADDR_team2InGameTeamPlayers             (0x012B2A)  // players[0]
#define ADDR_team1ShotChanceTable               (0x012F00)  // 60 bytes
#define ADDR_team2ShotChanceTable               (0x012F40)  // 60 bytes
#define ADDR_team1NameStorage                   (0x012F80)  // 18 bytes
#define ADDR_team2NameStorage                   (0x012F94)  // 18 bytes
#define ADDR_m_fadeAndSaveReplay                (0x012FB0)  // word (bool 0/1)
#define ADDR_m_fadeAndInstantReplay             (0x012FB2)  // word
#define ADDR_gl_isPaused                        (0x012FB4)  // word
#define ADDR_gl_statsEnqueued                   (0x012FB6)  // word
#define ADDR_res_scorersDirtyFlag               (0x012FB8)  // word
#define ADDR_breakState                         (0x012FBA)  // word
#define ADDR_m_goalCameraInterval               (0x012FBC)  // word — 55
#define ADDR_m_allowPlayerControlCameraInterval (0x012FBE)  // word — 550
#define ADDR_cameraCoordinatesValid             (0x012FC0)  // word
#define ADDR_ballOutOfGameTimer                 (0x012FC2)  // word
#define ADDR_writeOnlyVar03                     (0x012FC4)  // word
#define ADDR_g_autoSaveHighlights               (0x012FC6)  // word
#define ADDR_g_autoReplays                      (0x012FC8)  // word
#define ADDR_saveHighlightScene                 (0x012FCA)  // word
#define ADDR_instantReplayFlag                  (0x012FCC)  // word
#define ADDR_userRequestedReplay                (0x012FCE)  // word
#define ADDR_m_benchState                       (0x012FD0)  // word (BenchState enum)
#define ADDR_m_penaltiesInterval                (0x012FD2)  // word — 110
#define ADDR_m_playingMatch                     (0x012FD4)  // word (bool)
#define ADDR_kPlayerRunningAnimTableAddr        (0x013000)
#define ADDR_kPlayerStandingAnimTableAddr       (0x013100)
#define ADDR_kPlTacklingAnimTableAddr           (0x013200)
#define ADDR_kPlayerTackledAnimTableAddr        (0x013300)
#define ADDR_kGoalieCatchingBallAnimTableAddr   (0x013400)
#define ADDR_kAboutToThrowInAnimTableAddr       (0x013500)
#define ADDR_kThrowInPassAnimTableAddr          (0x013600)
#define ADDR_kThrowInKickAnimTableAddr          (0x013700)
#define ADDR_kLeftGoalieJumpingHighAnimTableAddr (0x013800)
#define ADDR_kRightGoalieJumpingHighAnimTableAddr (0x013900)
#define ADDR_kLeftGoalieJumpingLowAnimTableAddr (0x013A00)
#define ADDR_kRightGoalieJumpingLowAnimTableAddr (0x013B00)
#define ADDR_kStaticHeaderAttemptAnimTableAddr  (0x013C00)
#define ADDR_kStaticHeaderHitAnimTableAddr      (0x013D00)
#define ADDR_kJumpHeaderAttemptAnimTableAddr    (0x013E00)
#define ADDR_kJumpHeaderHitAnimTableAddr        (0x013F00)
#define ADDR_kPlInjuredAnimTableAddr            (0x014000)
#define ADDR_kFrameIndicesArraysBase            (0x014200)
#define ADDR_kFrameIndicesArraysEnd             (0x014FF0)
#define ADDR_dseg_17DEF4                        (0x015000)  // 28 × word = 56 bytes
#define ADDR_kGoalKeeperClaimingBallHeight      (0x015040)  // 7 × word = 14 bytes
#define ADDR_goal1TopSprite_ImageIndex          (0x015060)  // word
#define ADDR_goal2BottomSprite_ImageIndex       (0x015062)  // word
#define ADDR_playerMarkSprite_ImageIndex        (0x015064)  // word
#define ADDR_playerMarkSprite_XWhole            (0x015066)  // word
#define ADDR_playerMarkSprite_YWhole            (0x015068)  // word
#define ADDR_playerMarkSprite_ZWhole            (0x01506A)  // word
#define ADDR_displaySpritesDirtyFlag            (0x01506C)  // word
#define ADDR_gameRandValue                      (0x015070)  // word
#define ADDR_currentTick                        (0x015072)  // word
#define ADDR_longFireFlag                       (0x015074)  // word
#define ADDR_longFireTime                       (0x015076)  // word
