#!/usr/bin/env python3
"""Mechanically convert OpenSWOS SwosVm/Memory.cs's `Addr` constant block into
a C header, preserving names, values and comments verbatim.

This is the first step of the mechanical-port experiment (see
D:\\Programowanie\\SWOS_DS\\DEVLOG.md, 2026-09-15 entry): SwosVm.Memory.Addr.*
is the single source of truth for every memory offset the ported simulation
code reads/writes through. Hand-retyping ~380 constants risks silent
transcription errors, so this script parses the C# source and emits an
equivalent header mechanically, instead.

Usage:
    python convert_addr.py <path-to-Memory.cs> <output-swos_addr.h>

Only handles the patterns actually present in Memory.cs's Addr class:
    public const int NAME = DataBase + 0xNN;   // comment
    public const int NAME = 0xNN;               // comment
    public const int NAME = OTHER_NAME;          // alias
    public const int NAME = OTHER_NAME + NN;     // e.g. + 42
If a new pattern shows up (script raises), extend CONST_RE rather than
hand-editing the generated header.
"""
import re
import sys

CONST_RE = re.compile(
    r'^\s*(?:public|private)\s+const\s+int\s+(?P<name>\w+)\s*=\s*(?P<expr>[^;]+);'
    r'(?:\s*//\s*(?P<comment>.*))?$'
)

# Matches "DataBase + 0x1A4" / "DataBase+0x1A4" / "0x1A4" / "OtherName" / "OtherName + 42"
EXPR_RE = re.compile(
    r'^\s*(?:(?P<base>\w+)\s*\+\s*)?(?P<lit>0[xX][0-9A-Fa-f]+|\d+)\s*$'
    r'|^\s*(?P<alias>\w+)\s*$'
    r'|^\s*(?P<alias2>\w+)\s*\+\s*(?P<offs>\d+)\s*$'
)


def parse(path):
    # Pass 1: collect raw (name, expr, comment, lineno) in source order, since
    # C# class-member consts may forward-reference a sibling defined later.
    raw = []
    with open(path, encoding='utf-8') as f:
        in_addr = False
        depth = 0
        entered = False
        for lineno, line in enumerate(f, 1):
            if not in_addr:
                if 'public static class Addr' in line:
                    in_addr = True
                continue
            depth += line.count('{') - line.count('}')
            if depth > 0:
                entered = True
            if entered and depth == 0:
                break  # closed the Addr class's own braces
            m = CONST_RE.match(line)
            if not m:
                continue
            raw.append((m.group('name'), m.group('expr'), m.group('comment') or '', lineno))

    # Pass 2: resolve in dependency order (retry unresolved entries until a
    # full pass makes no progress -- handles forward references like
    # `aboutToThrowInAnimTable = kAboutToThrowInAnimTableAddr` at line 758,
    # defined at line 1351).
    values = {}
    pending = list(raw)
    entries_by_name = {}
    while pending:
        progressed = False
        still_pending = []
        for name, expr, comment, lineno in pending:
            em = EXPR_RE.match(expr)
            if not em:
                raise SystemExit(f'{path}:{lineno}: unhandled const expr: {expr!r}')
            try:
                if em.group('lit') is not None:
                    lit = int(em.group('lit'), 0)
                    base = em.group('base')
                    value = (values[base] if base else 0) + lit
                elif em.group('alias') is not None:
                    value = values[em.group('alias')]
                else:
                    value = values[em.group('alias2')] + int(em.group('offs'))
            except KeyError:
                still_pending.append((name, expr, comment, lineno))
                continue
            values[name] = value
            entries_by_name[name] = (name, value, comment)
            progressed = True
        if not progressed:
            unresolved = ', '.join(n for n, *_ in still_pending)
            raise SystemExit(f'{path}: could not resolve (unknown dependency): {unresolved}')
        pending = still_pending

    # Preserve original source order for readability of the generated header.
    return [entries_by_name[name] for name, _expr, _comment, _lineno in raw]


def emit(entries, out_path, source_path):
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by tools/convert_addr.py -- DO NOT EDIT BY HAND.\n')
        f.write(f'// Source: {source_path} (OpenSWOS SwosVm.Memory.Addr).\n')
        f.write('// Regenerate with: python tools/convert_addr.py <Memory.cs> include/swos_addr.h\n')
        f.write('#pragma once\n\n')
        for name, value, comment in entries:
            # ljust must never eat the required space before '(' -- a macro
            # name longer than the pad width would otherwise produce
            # `#define ADDR_LongName(0x...)`, which the preprocessor parses
            # as a function-like macro instead of an object-like one.
            macro = f'#define ADDR_{name}'
            macro = macro + ' ' if len(macro) >= 47 else macro.ljust(48)
            f.write(f'{macro}(0x{value:06X})')
            if comment:
                f.write(f'  // {comment}')
            f.write('\n')
    print(f'Wrote {len(entries)} address constants to {out_path}')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    entries = parse(sys.argv[1])
    emit(entries, sys.argv[2], sys.argv[1])
