#!/usr/bin/env python3
"""Mechanically extract TeamPort.cs's two shot-chance literal tables
(kGoalieSkillTables, kPlayerShotChanceTable) into a generated C header.

Reuses extract_table.py's brace-balanced text-extraction technique (see that
file's docstring for why: transcribing ~270 numbers by hand risks a silent
single-digit desync from the original). kGoalieSkillTables is a C# jagged
array (`short[][]`, `new short[8][] { new short[] {...}, ... }`) -- its
initializer syntax is NOT directly valid as a C fixed 2D array initializer
because of the `new short[] ` prefixes on each row, so this script strips
those (a mechanical text substitution, not a re-derivation of any values)
before emitting `int16_t kGoalieSkillTables[8][30] = { {...}, ... };`.

Usage: python extract_team_port_tables.py > include/generated/swos_team_port_tables.h
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_table import extract  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / "openswos/game/scripts/Sim/Port/TeamPort.cs"

goalie_body = extract(str(SOURCE), "kGoalieSkillTables")
goalie_body = re.sub(r"new short\[\]\s*", "", goalie_body)

shotchance_body = extract(str(SOURCE), "kPlayerShotChanceTable")

print("// Auto-generated by tools/extract_team_port_tables.py -- DO NOT EDIT BY HAND.")
print("// Source: openswos game/scripts/Sim/Port/TeamPort.cs.")
print("#pragma once")
print("#include <stdint.h>")
print()
print(f"// Mechanically extracted from {SOURCE} :: kGoalieSkillTables")
print(f"// (see tools/extract_team_port_tables.py -- `new short[]` prefixes")
print(f"// stripped mechanically so the C# jagged-array initializer parses as")
print(f"// a C fixed 2D array).")
print(f"static const int16_t swos_kGoalieSkillTables[8][30] = {goalie_body};")
print()
print(f"// Mechanically extracted from {SOURCE} :: kPlayerShotChanceTable")
print(f"// (see tools/extract_team_port_tables.py)")
print(f"static const int16_t swos_kPlayerShotChanceTable[30] = {shotchance_body};")
