// GENERATED by tools/convert_player_controlled.py from the real
// OpenSWOS PlayerControlled.cs. Do not hand-edit the generated control flow.
#include "swos_player_controlled.h"

#include <assert.h>
#include <stdint.h>

#include "swos_addr.h"
#include "swos_ai_brain.h"
#include "swos_ai_helpers.h"
#include "swos_ball_sprite.h"
#include "swos_memory.h"
#include "swos_player_actions.h"
#include "swos_player_header.h"
#include "swos_player_sprite.h"
#include "swos_player_tackle.h"
#include "swos_player_update.h"
#include "swos_team_data.h"

enum {
    OffOpponentsTeam = 0, OffPlayerNumber = 4, OffControlledPlayer = 32,
    OffPassToPlayerPtr = 36, OffPlayerHasBall = 40, OffAllowedDirections = 42,
    OffCurrentAllowedDir = 44, OffQuickFire = 48, OffNormalFire = 49,
    OffFirePressed = 50, OffFireThisFrame = 51, OffHeaderOrTackle = 52,
    OffShooting = 58, OffPlVeryCloseToBall = 61, OffPlCloseToBall = 62,
    OffPlNotFarFromBall = 63, OffBallLessEqual4 = 64, OffBall4To8 = 65,
    OffBall8To12 = 66, OffBall12To17 = 67, OffBallAbove17 = 68,
    OffPrevPlVeryClose = 69, OffLastHeadingPlayer = 72, OffGoalieSavedTimer = 76,
    OffPassingToPlayer = 90, OffBallInPlay = 94, OffBallOutOfPlay = 96,
    OffPassKickTimer = 102, OffPassingKickingPlayer = 104, OffOfs108 = 108,
    OffBallCanBeControlled = 110, OffBallCtrlPlDirection = 112,
    OffSpinTimer = 118, OffWonTheBallTimer = 138,
    SOffPlayerOrdinal = 2, SOffX = 32, SOffY = 36, SOffDirection = 42,
    SOffShooting = 58, SOffDestX = 58, SOffDestY = 60,
    SOffBallDistance = 74, SOffZWhole = 40,
};

SwosPlayerControlledTelemetry g_swosPcTelemetry;
// Step 9 closes the 6A/6B boundary: these hooks are now statically wired to
// the real AiBrain.SetControlsDirection / AiHelpers.AI_Kick implementations
// (not left NULL for an assert to catch) -- kept as function pointers,
// rather than direct calls, because that's the stable call point 6A/7B
// already established and other code (tests, future overrides) may still
// want to substitute a different AI at this seam.
SwosAiSetControlsDirectionHook g_swosAiSetControlsDirectionHook = swosAiBrainSetControlsDirection;
SwosAiKickHook g_swosAiKickHook = swosAiHelpersAiKick;
bool g_swosFaithfulBallControl = true;

static void runPassChaseTail(int spriteAddr, int teamBase);
static void runChaseBall(int spriteAddr, int teamBase);
static void applyKBallFrictionOrFallback(int spriteAddr, int teamBase);

void swosPlayerControlledResetTelemetry(void) {
    g_swosPcTelemetry = (SwosPlayerControlledTelemetry){0};
}

void swosPlayerControlledIncSkillDuelOwnWin(void) {
    g_swosPcTelemetry.skillDuelOwnWin++;
}

void swosPlayerControlledIncSkillDuelOppWin(void) {
    g_swosPcTelemetry.skillDuelOppWin++;
}

static void requireAiSetControlsDirection(int teamBase) {
    // Defensive only, post-step-9: the hook is always wired (see the
    // static initializer above). Kept as a named call site for readability
    // and so a test can still null the hook out deliberately.
    assert(g_swosAiSetControlsDirectionHook != 0);
    if (g_swosAiSetControlsDirectionHook)
        g_swosAiSetControlsDirectionHook(teamBase);
}

static void requireAiKick(int spriteAddr, int teamBase) {
    assert(g_swosAiKickHook != 0);
    if (g_swosAiKickHook)
        g_swosAiKickHook(spriteAddr, teamBase);
}

SwosPlayerControlledExit swosRunControlledBranch(int spriteAddr, bool topTeam)
{
    // A1 = spriteAddr; A6 = teamBase; A0 = opponentTeamBase; A2 = ballSprite.
    int teamBase     = swosTeamDataBase(topTeam);
    int opponentBase = swosTeamDataBase(!topTeam);
    int ballSprite   = BALLSPR_BASE;

    // updatePlayers.cpp:4398 — l_its_controlled_player:
    // updatePlayers.cpp:4399-4418 — playingPenalties != 0 AND gameState != ST_PENALTIES → bail out.
    int16_t ax;
    ax = swosReadSignedWord(ADDR_playingPenalties);
    if (ax != 0)
    {
        int16_t gameStateVal = swosReadSignedWord(ADDR_gameState);
        // cmp gameState, ST_PENALTIES (31)
        if (gameStateVal != 31)
        {
            return SWOS_PC_UPDATE_SPEED;
        }
    }

    // l_check_for_cpu_team: updatePlayers.cpp:4420-4436.
    // If playerNumber == 0 (CPU/AI team), run AI_SetControlsDirection.
    int16_t playerNumber = swosReadSignedWord(teamBase + OffPlayerNumber);
    if (playerNumber == 0)
    {
        // Real port — updatePlayers.cpp:15980 → AiBrain.SetControlsDirection.
        // Asm sig takes A6 (teamBase) only; the spriteAddr is implicit via
        // team.controlledPlayer. Pass teamBase.
        requireAiSetControlsDirection(teamBase);

        // === DRIBBLE-PIN FALLBACK (RETAINED 2026-06-01) ===================
        // This branch is a STAND-IN for the asm's natural cad write path,
        // not a deviation from it.
        //
        // In retail SWOS, when the AI team owns the ball, AiBrain.SetControls-
        // Direction always commits a non-negative cad before returning:
        //   - `l_theres_a_player_near` calls AI_DecideWhetherToTriggerFire
        //     which writes cad (via the "candidate #1" rotate) when the
        //     facing+Z windows match, OR falls through to the chase tree at
        //     cseg_84A0D → cseg_84AEB / cseg_84DD3 → cseg_84DE0 / cseg_84E16
        //     which writes cad either from D5 (ball-angle bucket) or from
        //     sprite.direction directly.
        //   - `l_noone_near → l_pass_to_player_too_far_or_null →
        //     l_decide_if_flipping_direction / l_use_current_player_direction`
        //     also writes cad on every branch.
        //
        // OpenSwos AiBrain reproduces those paths, but several gates depend
        // on TEAM-LEVEL flags that the per-sprite dispatcher only computes
        // for the LAST sprite in the bucket loop (plVeryCloseToBall,
        // plCloseToBall, frameCount &0x7F at cseg_84D10, etc.). Because we
        // call AiBrain per AI sprite (not once per team like the asm), some
        // mid-loop calls hit unpopulated team flags and AiBrain returns
        // early at the `l_theres_a_player_near` AI_DecideWhetherToTriggerFire
        // no_fire exit (no cad written). Telemetry confirms this is the
        // edge: `[ai-fire] cseg_850F9=8 cseg_84FCA=29` over 3000 ticks —
        // the fire-commit paths run, but the chase-only paths (which only
        // *write* cad without firing) don't get reached for every sprite.
        //
        // The compensating write below mirrors the asm's
        // `cseg_84E16: writeMemory(esi + 44, 2, [A5+Sprite.direction])`
        // (updatePlayers.cpp:18011-18014) — same source register, same
        // destination field. Gating on `playerHasBall != 0` restricts it to
        // the carrier-tick condition the upstream chase tree would also be
        // running under. Without this, cseg_80FFD →
        // CalculateIfPlayerWinsBall is skipped because cseg_80ECF gates on
        // `cad >= 0` (PlayerControlled.cs:534) and the ball stays at rest
        // while the carrier walks past it.
        //
        // TODO drop once AiBrain is restructured to run once per team
        // (asm-faithful dispatch) instead of once per AI sprite.
        //
        // Source: external/swos-port/src/game/updatePlayers/updatePlayers.cpp:18011-18014
        //         (cseg_84E16 — writes cad = A5.direction unconditionally).
        int16_t adFix = swosReadSignedWord(teamBase + OffCurrentAllowedDir);
        if (adFix < 0)
        {
            int16_t hasBallFix = swosReadSignedWord(teamBase + OffPlayerHasBall);
            if (hasBallFix != 0)
            {
                int ctrlFix = swosReadSignedDword(teamBase + OffControlledPlayer);
                if (ctrlFix != 0)
                {
                    int16_t spriteDirFix = swosReadSignedWord(ctrlFix + SOffDirection);
                    if (spriteDirFix >= 0 && spriteDirFix < 8)
                    {
                        swosWriteWord(teamBase + OffCurrentAllowedDir, spriteDirFix);
                    }
                }
            }
        }

        // === AI-FIRE FALLBACK (REMOVED 2026-06-01) =======================
        // Was: write team.currentAllowedDirection = sprite.direction and
        // normalFire = 1 when AiBrain.SetControlsDirection left the team in
        // an unprimed-but-ball-owning state. Empirically dead: 3000-tick
        // smoke shows the AiBrain cseg_84FCA path (updatePlayers.cpp:18229)
        // and cseg_850F9 path (18487) already commit normalFire on the
        // canonical path — the FIRE FALLBACK counter measured 0/0 events
        // every run before this removal, so the block was pure scaffolding.
        // Telemetry counters s_fireFallbackTop/Bot retained (always 0) for
        // Main.cs:713 API compatibility.
        //
        // Source: external/swos-port/src/game/updatePlayers/
        //   updatePlayers.cpp:18229 (cseg_84FCA) + :18487 (cseg_850F9).
    }

    // cseg_80C0C: updatePlayers.cpp:4438-4449.
    // allowedDirections = playerHasBall; playerHasBall = 0.
    ax = swosReadSignedWord(teamBase + OffPlayerHasBall);
    swosWriteWord(teamBase + OffAllowedDirections, ax);
    swosWriteWord(teamBase + OffPlayerHasBall, 0);
    // shooting reset unless firePressed != 0.
    int16_t shooting = swosReadSignedWord(teamBase + OffShooting);
    if (shooting != 0)
    {
        uint8_t firePressed = swosReadByte(teamBase + OffFirePressed);
        if (firePressed == 0)
        {
            swosWriteWord(teamBase + OffShooting, 0);
        }
    }

    // cseg_80C56: updatePlayers.cpp:4461-4473. gameStatePl != 100 → break-handling path.
    int16_t gameStatePl = swosReadSignedWord(ADDR_gameStatePl);
    if (gameStatePl == 100)
    {
        goto l_skip_break_handling;
    }

    // updatePlayers.cpp:4475-4486. lastTeamPlayedBeforeBreak != A6 → bail out.
    {
        int lastTeamPlayedBeforeBreak = swosReadSignedDword(ADDR_lastTeamPlayedBeforeBreak);
        if (teamBase != lastTeamPlayedBeforeBreak)
        {
            return SWOS_PC_UPDATE_SPEED;
        }
    }

    // updatePlayers.cpp:4488-4509. If (1 << sprite.direction) NOT in
    // playerTurnFlags → cameraDirection override + dseg_132806++.
    // updatePlayers.cpp:4488: ax = sprite.direction.
    int16_t spriteDirection = swosReadSignedWord(spriteAddr + SOffDirection);
    int16_t d0 = spriteDirection;
    {
        // shl ax, cl where ax=1, cl=spriteDirection. Mask cl to 5 bits.
        int shift = d0 & 0x1F;
        int mask = (1 << shift) & 0xFFFF;
        uint8_t playerTurnFlags = swosReadByte(ADDR_playerTurnFlags);
        int test = playerTurnFlags & mask;
        if (test == 0)
        {
            // cseg_80CB3 fall-through path (NOT taken means we entered this if).
            // Actually asm: jnz cseg_80CB3 → if zero we enter this block (override).
            int16_t cameraDir = swosReadSignedWord(ADDR_cameraDirection);
            swosWriteWord(spriteAddr + SOffDirection, cameraDir);
            int16_t cnt = swosReadSignedWord(ADDR_dseg_132806);
            swosWriteWord(ADDR_dseg_132806, (int16_t)(cnt + 1));
        }
    }

    // cseg_80CB3: updatePlayers.cpp:4522-4544.
    // Same test again with possibly-updated sprite.direction; if STILL fails,
    // we go into the find-loop to pick any acceptable direction.
    spriteDirection = swosReadSignedWord(spriteAddr + SOffDirection);
    d0 = spriteDirection;
    {
        int shift = d0 & 0x1F;
        int mask = (1 << shift) & 0xFFFF;
        uint8_t playerTurnFlags = swosReadByte(ADDR_playerTurnFlags);
        int test = playerTurnFlags & mask;
        if (test != 0) goto l_turn_flags_acceptable;
    }

    // updatePlayers.cpp:4546-4574 — find_acceptable_turn_flags_loop.
    // D0 = 7; while (--D0 >= 0) if (playerTurnFlags & (1<<D0)) break.
    d0 = 7;
l_find_acceptable_turn_flags_loop:
    {
        int shift = d0 & 0x1F;
        int mask = (1 << shift) & 0xFFFF;
        uint8_t playerTurnFlags = swosReadByte(ADDR_playerTurnFlags);
        int test = playerTurnFlags & mask;
        if (test != 0) goto l_created_acceptable_turn_flags;
        d0 = (int16_t)(d0 - 1);
        if (d0 >= 0) goto l_find_acceptable_turn_flags_loop;
        d0 = 0;
    }
l_created_acceptable_turn_flags:
    // updatePlayers.cpp:4578-4590.
    swosWriteWord(ADDR_cameraDirection, d0);
    swosWriteWord(spriteAddr + SOffDirection, d0);
    {
        int16_t cnt = swosReadSignedWord(ADDR_deadThrowInDirectionVar);
        swosWriteWord(ADDR_deadThrowInDirectionVar, (int16_t)(cnt + 1));
    }

l_turn_flags_acceptable:
    // updatePlayers.cpp:4592-4615.
    // If playerNumber == 0 (CPU) AND stoppageTimerActive > 55 → l_hide_result.
    playerNumber = swosReadSignedWord(teamBase + OffPlayerNumber);
    if (playerNumber == 0)
    {
        int16_t stoppageActive = swosReadSignedWord(ADDR_stoppageTimerActive);
        if (stoppageActive > 55)
        {
            goto l_hide_result;
        }
        goto l_test_fire;
    }

    // cseg_80D49: updatePlayers.cpp:4617-4625. If currentAllowedDirection < 0 (sign set)
    // → l_joy_any_fire_pressed.
    {
        int16_t cad = swosReadSignedWord(teamBase + OffCurrentAllowedDir);
        if (cad < 0) goto l_joy_any_fire_pressed;
    }

l_test_fire:
    // updatePlayers.cpp:4627-4651. Fire/quickFire/normalFire uint8_t tests.
    {
        uint8_t v = swosReadByte(teamBase + OffFirePressed);
        if (v != 0) goto l_joy_any_fire_pressed;
        v = swosReadByte(teamBase + OffQuickFire);
        if (v != 0) goto l_joy_any_fire_pressed;
        v = swosReadByte(teamBase + OffNormalFire);
        if (v == 0) goto l_test_direction;
    }

l_joy_any_fire_pressed:
    // updatePlayers.cpp:4653-4662. If statsTimer != 0 → fireBlocked = 1, else hide result.
    {
        int16_t st = swosReadSignedWord(ADDR_statsTimer);
        if (st == 0) goto l_hide_result;
        swosWriteWord(ADDR_fireBlocked, 1);
    }

l_hide_result:
    // updatePlayers.cpp:4664-4674. timeVar = -timeVar; resultTimer = -resultTimer.
    {
        int16_t t = swosReadSignedWord(ADDR_timeVar);
        swosWriteWord(ADDR_timeVar, (int16_t)(-t));
        int r = swosReadSignedDword(ADDR_resultTimer);
        swosWriteDword(ADDR_resultTimer, -r);
    }

l_test_direction:
    // updatePlayers.cpp:4676-4691. currentAllowedDirection < 0 → set from sprite.direction
    // then jump to l_skip_break_handling. Else fall through to test playerTurnFlags.
    {
        int16_t cad = swosReadSignedWord(teamBase + OffCurrentAllowedDir);
        d0 = cad;
        if (cad < 0)
        {
            // cseg_80DB6 — sprite.direction → currentAllowedDirection.
            int16_t dir = swosReadSignedWord(spriteAddr + SOffDirection);
            swosWriteWord(teamBase + OffCurrentAllowedDir, dir);
            goto l_skip_break_handling;
        }
    }

    // cseg_80DCC: updatePlayers.cpp:4694-4717. Mask test against playerTurnFlags.
    {
        int shift = d0 & 0x1F;
        int mask = (1 << shift) & 0xFFFF;
        uint8_t playerTurnFlags = swosReadByte(ADDR_playerTurnFlags);
        int test = playerTurnFlags & mask;
        if (test == 0)
        {
            // Failed → cseg_80DB6 (re-snap from sprite.direction).
            int16_t dir = swosReadSignedWord(spriteAddr + SOffDirection);
            swosWriteWord(teamBase + OffCurrentAllowedDir, dir);
            goto l_skip_break_handling;
        }
        // Pass → write d0 to sprite.direction, then call UpdatePlayerWithBall.
        swosWriteWord(spriteAddr + SOffDirection, d0);
        // Real port — player.cpp:85 → PlayerActions.UpdatePlayerWithBall.
        swosUpdatePlayerWithBall(spriteAddr);
    }

l_skip_break_handling:
    // updatePlayers.cpp:4720-4728. If sprite[+40].playerHasBall != 0 → exit.
    // NOTE: The asm reads esi+40 with esi=A1 — that is sprite[40]. Sprite
    // does NOT have a "playerHasBall" field at +40; this is treated as
    // word access on the sprite struct (PlayerSprite layout). We mirror.
    ax = swosReadSignedWord(spriteAddr + 40);
    if (ax != 0) return SWOS_PC_UPDATE_SPEED;

    // updatePlayers.cpp:4730-4743. currentAllowedDirection >= 0 (sign clear)
    // → skip; else copy sprite.x/y to sprite.destX/destY.
    {
        int16_t cad = swosReadSignedWord(teamBase + OffCurrentAllowedDir);
        if (cad < 0)
        {
            int16_t sx = swosReadSignedWord(spriteAddr + SOffX);
            swosWriteWord(spriteAddr + SOffDestX, sx);
            int16_t sy = swosReadSignedWord(spriteAddr + SOffY);
            swosWriteWord(spriteAddr + SOffDestY, sy);
        }
    }

    // cseg_80E41: updatePlayers.cpp:4745-4790.
    // If gameStatePl == 100 AND quickFire == 0 AND shooting == 0
    //    AND (plVeryCloseToBall != 0 OR plCloseToBall != 0)
    //    AND opponentsTeam → l_ball_becomes_free chain at cseg_80E8F.
    gameStatePl = swosReadSignedWord(ADDR_gameStatePl);
    if (gameStatePl != 100) goto l_test_quick_fire;
    {
        int16_t qf = swosReadSignedWord(teamBase + OffQuickFire);
        if (qf != 0) goto l_test_quick_fire;
        int16_t sh = swosReadSignedWord(teamBase + OffShooting);
        if (sh != 0) goto l_test_quick_fire;
        uint8_t pvc = swosReadByte(teamBase + OffPlVeryCloseToBall);
        if (pvc != 0) goto cseg_80E8F;
        uint8_t pcb = swosReadByte(teamBase + OffPlCloseToBall);
        if (pcb == 0) goto cseg_80ECF;
    }

cseg_80E8F:
    // updatePlayers.cpp:4792-4810. If allowedDirections == 0 → clear unkBallTimer.
    // Set playerHasBall = 1; set opponent.spinTimer = -1.
    {
        int16_t adp = swosReadSignedWord(teamBase + OffAllowedDirections);
        if (adp == 0)
        {
            swosWriteWord(teamBase + OffOfs108, 0);
        }
        swosWriteWord(teamBase + OffPlayerHasBall, 1);
        swosWriteWord(opponentBase + OffSpinTimer, -1);

        // === PER-TICK BALL PIN (2026-06-01) ============================
        // Wire updateControllingPlayer here so the ball gets glued to the
        // carrier each tick they have it — not just on pass receipt.
        //
        // In the upstream C++ port `updateControllingPlayer` is only
        // called once from the pass-receipt commit at
        // external/swos-port/src/game/updatePlayers/updatePlayers.cpp:8252
        // (the cseg_82D59 swap of passToPlayerPtr → controlledPlayer).
        // From then on the real game keeps the ball ahead of the runner
        // via calculateIfPlayerWinsBall's "nudge ball forward" branch
        // (external/swos-port/src/game/player.cpp:442-685) plus the
        // continuous physics update — the chasing ball never escapes
        // because player speed >= ball speed when controlled.
        //
        // Our port's physics + AI chase are still partially stubbed, so
        // a loose ball at kick-off never gets pinned without first being
        // passed, and the carrier's plVeryCloseToBall gate (32 sq-px)
        // is too tight for a ball travelling at ~2200 vs a player at
        // ~970. Calling UpdateControllingPlayer here each tick the
        // carrier is plVeryCloseToBall OR plCloseToBall (the very gate
        // that brought us into cseg_80E8F) restores the canonical
        // ±1 px glue from external/swos-port/src/game/player.cpp:135-191
        // and lets us roll back the temporary widened gate in
        // UpdatePlayerBallDistanceAndHeight (UpdatePlayers.cs:1112-1115)
        // to the original 32 sq-px.
        //
        // Keeper ordinal (==1) handled separately because the keeper
        // uses kBallPlOffsets's keeper variant in
        // updateBallWithControllingGoalkeeper (player.cpp:200-265).
        // Source: external/swos-port/src/game/updatePlayers/updatePlayers.cpp:8235-8252
        //         (pass-receipt path branches on ordinal exactly like this).
        //
        // === PIN POSSESSION GATE (2026-07-02, duel ping-pong fix) ======
        // The pin is a compensating hack NOT present in the original —
        // asm cseg_80E8F/cseg_80EAA (updatePlayers.cpp:4792-4810) only
        // sets playerHasBall=1 + opponent.spinTimer=-1 and never moves
        // the ball. Because this block runs BEFORE the wonTheBallTimer
        // gate at cseg_80FFD (updatePlayers.cpp:4936-4960, ported below
        // at label cseg_80FFD) and before the CalculateIfPlayerWinsBall
        // duel (player.cpp:276-440), an ungated pin lets:
        //   (a) a team locked out by a lost duel / tackle
        //       (wonTheBallTimer != 0, swos.asm:108151 "= 12" /
        //       swos.asm:115891 "= 12" / swos.asm:108310 "= 8") still
        //       physically yank the ball to its player's feet, and
        //   (b) a challenger grab the ball off a legitimate holder with
        //       a bare touch, when the original requires winning the
        //       CalculateIfPlayerWinsBall skill duel first
        //       (player.cpp:283-305 gates: opponent.wonTheBallTimer == 0
        //       AND opponent.playerHasBall != 0 AND opponent moving).
        // Both produced the user-visible "possession flips back and
        // forth every tick" bug. Gate the pin (and ONLY the pin — the
        // playerHasBall/spinTimer/unkBallTimer writes above stay
        // unconditional, faithful to cseg_80EAA) on the same conditions
        // under which the original lets this team's player control the
        // ball this tick:
        //   - own wonTheBallTimer == 0   (cseg_81028 skip,
        //     updatePlayers.cpp:4954-4960)
        //   - NOT (opponent holds the ball AND opponent is not locked
        //     out) — that contested case is decided by the duel below,
        //     not by a touch-steal (player.cpp:283-305).
        int16_t pinOwnWbt   = swosReadSignedWord(teamBase + OffWonTheBallTimer);
        int16_t pinOppHas   = swosReadSignedWord(opponentBase + OffPlayerHasBall);
        int16_t pinOppWbt   = swosReadSignedWord(opponentBase + OffWonTheBallTimer);
        bool  pinAllowed  = pinOwnWbt == 0 && !(pinOppHas != 0 && pinOppWbt == 0);
        if (pinAllowed)
        {
            int16_t pinOrdinal = swosReadSignedWord(spriteAddr + SOffPlayerOrdinal);
            if (pinOrdinal == 1)
            {
                // Keeper glue is canonical (updateBallWithControllingGoalkeeper) — always on.
                swosUpdateBallWithControllingGoalkeeper(spriteAddr);
                g_swosPcTelemetry.pinControlledPerTick++;
            }
            else if (!g_swosFaithfulBallControl)
            {
                // Outfield per-tick pin = the non-original hack that masks the
                // CONTROL skill. OFF by default (FaithfulBallControl) so the ball
                // runs away from weak dribblers per CalculateIfPlayerWinsBall.
                swosUpdateControllingPlayer(spriteAddr);
                g_swosPcTelemetry.pinControlledPerTick++;
            }
        }
    }

cseg_80ECF:
    // updatePlayers.cpp:4812-5045. The MAIN "ball control" arbitration block.
    // currentAllowedDirection < 0 (sign set) → check various paths;
    //   else (>= 0) → cseg_80FFD (we have a directional input).
    {
        int16_t cad = swosReadSignedWord(teamBase + OffCurrentAllowedDir);
        d0 = cad;
        if (cad >= 0) goto cseg_80FFD;

        // playerNumber == 0 (CPU) → l_jmp_update_player_speed.
        int16_t pn = swosReadSignedWord(teamBase + OffPlayerNumber);
        if (pn == 0) return SWOS_PC_UPDATE_SPEED;

        // sprite.playerOrdinal == 1 (goalkeeper) → l_jmp_update_player_speed.
        int16_t ord = swosReadSignedWord(spriteAddr + SOffPlayerOrdinal);
        if (ord == 1) return SWOS_PC_UPDATE_SPEED;

        // fireThisFrame == 0 → exit.
        uint8_t ftf = swosReadByte(teamBase + OffFireThisFrame);
        if (ftf == 0) return SWOS_PC_UPDATE_SPEED;

        // currentAllowedDirection (re-read) >= 0 → exit (signed comparison;
        // we already know <0, but asm re-checks here; keep parity).
        int16_t cad2 = swosReadSignedWord(teamBase + OffCurrentAllowedDir);
        if (cad2 >= 0) return SWOS_PC_UPDATE_SPEED;

        // ball-distance bucket check. plVeryCloseToBall | plCloseToBall | plNotFarFromBall must be set.
        uint8_t pvc = swosReadByte(teamBase + OffPlVeryCloseToBall);
        uint8_t pcb = swosReadByte(teamBase + OffPlCloseToBall);
        uint8_t pnf = swosReadByte(teamBase + OffPlNotFarFromBall);
        if (pvc == 0 && pcb == 0 && pnf == 0) return SWOS_PC_UPDATE_SPEED;

        // cseg_80F61: ball-height bucket check. ball8To12 | ball12To17 | ballAbove17.
        uint8_t b8 = swosReadByte(teamBase + OffBall8To12);
        uint8_t b12 = swosReadByte(teamBase + OffBall12To17);
        uint8_t ba = swosReadByte(teamBase + OffBallAbove17);
        if (b8 == 0 && b12 == 0 && ba == 0) return SWOS_PC_UPDATE_SPEED;

        // cseg_80F88: trigger static header.
        swosWriteWord(teamBase + OffHeaderOrTackle, 1);
        // D0 = sprite.direction (passed as the direction arg to the real port).
        int16_t headerDir = swosReadSignedWord(spriteAddr + SOffDirection);
        // Real port — updatePlayers.cpp:15803 → PlayerHeader.AttemptStaticHeader.
        swosAttemptStaticHeader(spriteAddr, headerDir);
        swosWriteDword(teamBase + OffLastHeadingPlayer, spriteAddr);
        swosWriteWord(teamBase + OffBallCanBeControlled, 0);
        return SWOS_PC_UPDATE_SPEED;
    }

cseg_80FFD:
    g_swosPcTelemetry.enterCseg80FFD++;
    // updatePlayers.cpp:4936-4960. opponent.playerHasBall == 0 → clear our wonTheBallTimer.
    // Then if wonTheBallTimer != 0 → goto cseg_81793 (pitch-clamp branch).
    {
        int16_t oppHas = swosReadSignedWord(opponentBase + OffPlayerHasBall);
        if (oppHas == 0)
        {
            swosWriteWord(teamBase + OffWonTheBallTimer, 0);
        }
        int16_t wbt = swosReadSignedWord(teamBase + OffWonTheBallTimer);
        if (wbt != 0) goto cseg_81793;
    }

    // updatePlayers.cpp:4962-4994. ball-distance / ball-height bucket gates.
    {
        uint8_t pvc = swosReadByte(teamBase + OffPlVeryCloseToBall);
        if (pvc == 0) goto l_test_quick_fire;
        uint8_t ba = swosReadByte(teamBase + OffBallAbove17);
        if (ba != 0) goto l_test_quick_fire;
        uint8_t b12 = swosReadByte(teamBase + OffBall12To17);
        if (b12 != 0) goto l_test_quick_fire;

        // cseg_8108A: updatePlayers.cpp:4986-4994.
        uint8_t pvp = swosReadByte(teamBase + OffPrevPlVeryClose);
        if (pvp == 0)
        {
            swosWriteWord(teamBase + OffBallCanBeControlled, 0);
        }
    }

    // cseg_8108A: updatePlayers.cpp:4996-5042 — ball becomes free, log this team played.
    {
        int16_t bcpd = swosReadSignedWord(teamBase + OffBallCtrlPlDirection);
        // The asm compares D0 (currentAllowedDirection) against ball-controlling-player-direction
        // and clears ballCanBeControlled if they differ.
        if (d0 != bcpd)
        {
            swosWriteWord(teamBase + OffBallCanBeControlled, 0);
        }
    }

    // l_ball_becomes_free: updatePlayers.cpp:5013-5044. ballCanBeControlled++ then
    // record this team as the ball-handler.
    {
        int16_t bcc = swosReadSignedWord(teamBase + OffBallCanBeControlled);
        int16_t bccNew = (int16_t)(bcc + 1);
        swosWriteWord(teamBase + OffBallCanBeControlled, bccNew);
        // D1 = ballCanBeControlled (new value); written below.
        int16_t newDirection = d0;
        swosWriteWord(teamBase + OffBallCtrlPlDirection, newDirection);
        swosWriteDword(ADDR_lastTeamPlayed, teamBase);
        swosWriteDword(ADDR_lastPlayerPlayed, spriteAddr);
        swosWriteWord(ADDR_penalty, 0);
        swosWriteWord(ADDR_playerHadBall, 0);
        int16_t oppHas = swosReadSignedWord(opponentBase + OffPlayerHasBall);
        if (oppHas != 0)
        {
            swosWriteWord(ADDR_playerHadBall, 1);
        }
    }

    // l_calculate_if_player_wins_ball: updatePlayers.cpp:5046-5064.
    // Real port — player.cpp:276 → PlayerActions.CalculateIfPlayerWinsBall.
    // D0 = currentAllowedDirection (held in local `d0` since cseg_80ECF line 377).
    g_swosPcTelemetry.reachedCwbCall++;
    // (2026-07-02: PlayerActions.CalculateIfPlayerWinsBall now addresses
    // wonTheBallTimer at the correct +138 offset directly — the temporary
    // +130 mirror shim that lived here has been deleted.)
    swosCalculateIfPlayerWinsBall(d0, teamBase, spriteAddr);
    swosWriteWord(opponentBase + OffSpinTimer, -1);
    swosWriteWord(opponentBase + OffPassingToPlayer, 0);
    swosWriteDword(opponentBase + OffPassingKickingPlayer, 0);
    goto cseg_81793;

l_test_quick_fire:
    // updatePlayers.cpp:5067-5075. quickFire = 0 → l_no_passing.
    {
        uint8_t qf = swosReadByte(teamBase + OffQuickFire);
        if (qf == 0) goto l_no_passing;
    }
    // updatePlayers.cpp:5077-5100.
    {
        int16_t cad = swosReadSignedWord(teamBase + OffCurrentAllowedDir);
        d0 = cad;
        if (cad < 0) goto l_no_passing;
        uint8_t pvc = swosReadByte(teamBase + OffPlVeryCloseToBall);
        if (pvc == 0)
        {
            uint8_t pcb = swosReadByte(teamBase + OffPlCloseToBall);
            if (pcb == 0) goto l_no_passing;
        }
    }
    // cseg_811DF: updatePlayers.cpp:5102-5134. gameStatePl != 100 → test turn flags.
    {
        int16_t gsp = swosReadSignedWord(ADDR_gameStatePl);
        if (gsp != 100)
        {
            int shift = d0 & 0x1F;
            int mask = (1 << shift) & 0xFFFF;
            uint8_t ptf = swosReadByte(ADDR_playerTurnFlags);
            if ((ptf & mask) == 0) goto l_no_passing;
        }
    }
    // cseg_81203: updatePlayers.cpp:5136-5158. sprite.playerOrdinal != 1 (not goalie)
    // requires ballLessEqual4 set; if 0 → no passing.
    {
        int16_t ord = swosReadSignedWord(spriteAddr + SOffPlayerOrdinal);
        if (ord != 1)
        {
            uint8_t ble4 = swosReadByte(teamBase + OffBallLessEqual4);
            if (ble4 == 0) goto l_no_passing;
        }
    }
    // cseg_81221: updatePlayers.cpp:5160-5237. Pass execution.
    {
        swosWriteDword(ADDR_lastTeamPlayed, teamBase);
        swosWriteDword(ADDR_lastPlayerPlayed, spriteAddr);
        swosWriteWord(ADDR_penalty, 0);
        swosWriteWord(ADDR_playerHadBall, 0);
        // A2 = ballSprite; writeMemory(esi + 40, 2, 0) — clear ball.z.whole.
        swosWriteWord(ballSprite + SOffZWhole, 0);
        // Real port — player.cpp:2560 → swosDoPass(teamBase, sprite).
        swosDoPass(teamBase, spriteAddr);
        swosWriteDword(teamBase + OffLastHeadingPlayer, spriteAddr);
        int16_t gsp = swosReadSignedWord(ADDR_gameStatePl);
        if (gsp != 100)
        {
            swosWriteWord(ADDR_gameNotInProgressCounterWriteOnly, 0);
        }
        // cseg_812C6: penalty check.
        int16_t gs = swosReadSignedWord(ADDR_gameState);
        if (gs == 14)
        {
            swosWriteWord(ADDR_penalty, 1);
        }
        // l_not_penalty: set gameStatePl=100 / gameState=100, mark in-play.
        swosWriteWord(ADDR_gameStatePl, 100);
        swosWriteWord(ADDR_gameState, 100);
        swosWriteWord(teamBase + OffBallInPlay, 1);
        swosWriteWord(teamBase + OffBallOutOfPlay, 1);
        swosWriteWord(opponentBase + OffBallInPlay, 1);
        swosWriteWord(opponentBase + OffBallOutOfPlay, 1);
        swosWriteWord(opponentBase + OffSpinTimer, -1);
        swosWriteDword(teamBase + OffControlledPlayer, 0);
        swosWriteDword(teamBase + OffPassingKickingPlayer, spriteAddr);
        swosWriteWord(teamBase + OffPassKickTimer, 25);
        swosWriteWord(teamBase + OffBallCanBeControlled, 0);
        // A0 = readMemory(esi, 4) — opponentsTeam. Already opponentBase.
        swosWriteWord(opponentBase + OffPassingToPlayer, 0);
        swosWriteDword(opponentBase + OffPassingKickingPlayer, 0);
        return SWOS_PC_STOP_PLAYER;
    }

l_no_passing:
    // updatePlayers.cpp:5239-5272. normalFire path (kicking ball).
    {
        uint8_t nf = swosReadByte(teamBase + OffNormalFire);
        if (nf == 0) goto l_check_if_goalkeeper;
        int16_t cad = swosReadSignedWord(teamBase + OffCurrentAllowedDir);
        d0 = cad;
        if (cad < 0) goto l_check_if_goalkeeper;
        uint8_t pvc = swosReadByte(teamBase + OffPlVeryCloseToBall);
        if (pvc == 0)
        {
            uint8_t pcb = swosReadByte(teamBase + OffPlCloseToBall);
            if (pcb == 0) goto l_check_if_goalkeeper;
        }
    }
    // cseg_813DA: updatePlayers.cpp:5274-5306. gameStatePl != 100 → check turn flags.
    {
        int16_t gsp = swosReadSignedWord(ADDR_gameStatePl);
        if (gsp != 100)
        {
            int shift = d0 & 0x1F;
            int mask = (1 << shift) & 0xFFFF;
            uint8_t ptf = swosReadByte(ADDR_playerTurnFlags);
            if ((ptf & mask) == 0) goto l_check_if_goalkeeper;
        }
    }
    // cseg_813FE: updatePlayers.cpp:5308-5330. playerOrdinal check for non-goalie.
    {
        int16_t ord = swosReadSignedWord(spriteAddr + SOffPlayerOrdinal);
        if (ord != 1)
        {
            uint8_t ble4 = swosReadByte(teamBase + OffBallLessEqual4);
            if (ble4 == 0) goto l_check_if_goalkeeper;
        }
    }
    // cseg_8141C: updatePlayers.cpp:5332-5407. Kick execution.
    {
        swosWriteDword(ADDR_lastTeamPlayed, teamBase);
        swosWriteDword(ADDR_lastPlayerPlayed, spriteAddr);
        swosWriteWord(ADDR_penalty, 0);
        swosWriteWord(ADDR_playerHadBall, 0);
        // === REMOVED (2026-07-05, tasks #188/#189): port-only goal-ward
        // reaim crutch ================================================
        // A 2026-06-01 stand-in used to OVERRIDE the kicker's direction
        // here, pointing it at the goal CENTRE (kGoalCentreX=336, goalY
        // 129/769) before every controlled kick — a non-faithful crutch
        // added before AiBrain's aim was wired, to stop bot strikers
        // shooting their own net. It is now both redundant and harmful:
        //   1. The faithful AI (AiBrain.SetControlsDirection +
        //      AiHelpers.AI_SetDirectionTowardOpponentsGoal / AI_Decide-
        //      WhetherToTriggerFire, updatePlayers.cpp:19461/19577) already
        //      steers the carrier to face the opponent goal before firing.
        //      Measured: 233/234 controlled kicks now aim at the correct
        //      enemy goal in a 30k-tick AI-vs-AI smoke, both halves.
        //   2. It forced every shot to the goal CENTRE — exactly where the
        //      keeper stands — so shots were saved and NEITHER team scored
        //      (1-0 one-way; task #188 "CPU never scores"). Removing it:
        //      2-2, both teams score, shots spread across the mouth.
        //   3. It ran for HUMAN kicks and PENALTIES too, overriding the
        //      player's own aim: a penalty aimed right was re-pointed at
        //      centre (task #189 "shot right → ball centre → deflect").
        // The faithful cseg_8141C path (updatePlayers.cpp:5332-5407) commits
        // the kick in the sprite's CURRENT direction — no reaim. We now do
        // exactly that: fall straight through to PlayerKickingBall.
        // ===============================================================
        // Real port — player.cpp:750 → swosPlayerKickingBall(teamBase, sprite).
        swosPlayerKickingBall(teamBase, spriteAddr);
        swosWriteDword(teamBase + OffLastHeadingPlayer, spriteAddr);
        int16_t gsp = swosReadSignedWord(ADDR_gameStatePl);
        if (gsp != 100)
        {
            swosWriteWord(ADDR_gameNotInProgressCounterWriteOnly, 0);
        }
        // cseg_814B5: penalty check.
        int16_t gs = swosReadSignedWord(ADDR_gameState);
        if (gs == 14)
        {
            swosWriteWord(ADDR_penalty, 1);
        }
        // l_not_penalty2: same set-state as l_not_penalty, plus shooting=1.
        swosWriteWord(ADDR_gameStatePl, 100);
        swosWriteWord(ADDR_gameState, 100);
        swosWriteWord(teamBase + OffBallInPlay, 1);
        swosWriteWord(teamBase + OffBallOutOfPlay, 1);
        swosWriteWord(opponentBase + OffBallInPlay, 1);
        swosWriteWord(opponentBase + OffBallOutOfPlay, 1);
        swosWriteWord(opponentBase + OffSpinTimer, -1);
        swosWriteDword(teamBase + OffControlledPlayer, 0);
        swosWriteDword(teamBase + OffPassingKickingPlayer, spriteAddr);
        swosWriteWord(teamBase + OffPassKickTimer, 25);
        swosWriteWord(teamBase + OffBallCanBeControlled, 0);
        // updatePlayers.cpp:5396-5402 — `mov esi, A6` precedes the
        // controlledPlayer/passingKicking/passKickTimer/ballCanBeControlled
        // writes AND `mov [esi+58], 1` — shooting=1 lands on the KICKER's
        // team. esi switches to A0 (opponent) only afterwards (5403-5404)
        // for the passingToPlayer/passingKickingPlayer clears below.
        swosWriteWord(teamBase + OffShooting, 1);
        swosWriteWord(opponentBase + OffPassingToPlayer, 0);
        swosWriteDword(opponentBase + OffPassingKickingPlayer, 0);
        return SWOS_PC_STOP_PLAYER;
    }

l_check_if_goalkeeper:
    // updatePlayers.cpp:5409-5497. Tackle attempt branch.
    // If sprite.playerOrdinal == 1 → cseg_8167F (no tackle, attempt header).
    {
        int16_t ord = swosReadSignedWord(spriteAddr + SOffPlayerOrdinal);
        if (ord == 1) goto cseg_8167F;
        uint8_t ftf = swosReadByte(teamBase + OffFireThisFrame);
        if (ftf == 0) goto cseg_8167F;
        int16_t cad = swosReadSignedWord(teamBase + OffCurrentAllowedDir);
        d0 = cad;
        if (cad < 0) goto cseg_8167F;
        uint8_t pnf = swosReadByte(teamBase + OffPlNotFarFromBall);
        if (pnf == 0) goto cseg_8167F;
        uint8_t ble4 = swosReadByte(teamBase + OffBallLessEqual4);
        if (ble4 == 0)
        {
            uint8_t b4 = swosReadByte(teamBase + OffBall4To8);
            if (b4 == 0) goto cseg_8167F;
        }
    }
    // cseg_815F7: updatePlayers.cpp:5466-5497. Tackle target choice check.
    {
        int passToPlayerPtr = swosReadSignedDword(teamBase + OffPassToPlayerPtr);
        // The A5 = passToPlayerPtr; if 0 → l_begin_tackling.
        if (passToPlayerPtr != 0)
        {
            int targetDist = swosReadSignedDword(passToPlayerPtr + SOffBallDistance);
            int ourDist = swosReadSignedDword(spriteAddr + SOffBallDistance);
            // cmp D1, eax; jb cseg_8167F (unsigned <).
            if ((uint32_t)targetDist < (uint32_t)ourDist) goto cseg_8167F;
        }
    }
    // l_begin_tackling: updatePlayers.cpp:5499-5513.
    swosWriteWord(teamBase + OffHeaderOrTackle, 1);
    // Real port — updatePlayers.cpp:14839 → PlayerTackle.PlayerBeginTackling.
    // D0 = currentAllowedDirection (held in local `d0` since cseg_8167F
    // line 658 above, mirroring the asm `mov D0, currentAllowedDirection`).
    swosPlayerBeginTackling(spriteAddr, teamBase, d0);
    swosWriteWord(teamBase + OffBallCanBeControlled, 0);
    return SWOS_PC_UPDATE_SPEED;

cseg_8167F:
    // updatePlayers.cpp:5515-5570. Jump-header path (non-goalie).
    {
        int16_t ord = swosReadSignedWord(spriteAddr + SOffPlayerOrdinal);
        if (ord == 1) goto l_not_a_header;
        uint8_t ftf = swosReadByte(teamBase + OffFireThisFrame);
        if (ftf == 0) goto l_not_a_header;
        int16_t cad = swosReadSignedWord(teamBase + OffCurrentAllowedDir);
        d0 = cad;
        if (cad < 0) goto l_not_a_header;
        uint8_t pvc = swosReadByte(teamBase + OffPlVeryCloseToBall);
        uint8_t pcb = swosReadByte(teamBase + OffPlCloseToBall);
        uint8_t pnf = swosReadByte(teamBase + OffPlNotFarFromBall);
        if (pvc == 0 && pcb == 0 && pnf == 0) goto l_not_a_header;
    }
    // cseg_816E5: updatePlayers.cpp:5572-5596.
    {
        uint8_t b8 = swosReadByte(teamBase + OffBall8To12);
        uint8_t b12 = swosReadByte(teamBase + OffBall12To17);
        uint8_t ba = swosReadByte(teamBase + OffBallAbove17);
        if (b8 == 0 && b12 == 0 && ba == 0) goto l_not_a_header;
    }
    // l_its_a_header: updatePlayers.cpp:5598-5614.
    swosWriteWord(teamBase + OffHeaderOrTackle, 1);
    // Real port — updatePlayers.cpp:15253 → PlayerHeader.PlayerAttemptingJumpHeader.
    // D0 = currentAllowedDirection (held in local `d0` since cseg_8167F line 686).
    swosPlayerAttemptingJumpHeader(spriteAddr, d0);
    swosWriteDword(teamBase + OffLastHeadingPlayer, spriteAddr);
    swosWriteWord(teamBase + OffBallCanBeControlled, 0);
    return SWOS_PC_UPDATE_SPEED;

l_not_a_header:
    // updatePlayers.cpp:5616-5638. gameStatePl != 100 OR currentAllowedDirection < 0 → exit.
    {
        int16_t gsp = swosReadSignedWord(ADDR_gameStatePl);
        if (gsp != 100) return SWOS_PC_UPDATE_SPEED;
        int16_t cad = swosReadSignedWord(teamBase + OffCurrentAllowedDir);
        d0 = cad;
        if (cad < 0) return SWOS_PC_UPDATE_SPEED;
    }

cseg_81793:
    // updatePlayers.cpp:5640-5778. Pitch-clamp + default-dest update.
    // D1 = sprite.x.whole; D2 = sprite.y.whole; D3 = 0 (out-of-pitch mask).
    int16_t d1 = swosReadSignedWord(spriteAddr + SOffX);
    int16_t d2 = swosReadSignedWord(spriteAddr + SOffY);
    int d3 = 0;
    // Each pitch-side test ORs a direction bitmask into D3.
    if (d1 < 79)    d3 |= 0xE0;  // left side → block dirs 5/6/7 (NW/W/SW)
// l_inside_pitch_left_x
    if (d1 > 592)   d3 |= 0x0E;  // right side → block dirs 1/2/3 (NE/E/SE)
// l_inside_pitch_right_x
    if (d2 < 127)   d3 |= 0x83;  // top → block dirs 0/7/1 ... actually 7,0,1 (N row)
// l_inside_pitch_top_y
    if (d2 > 771)   d3 |= 0x38;  // bottom → block dirs 3/4/5

// l_inside_pitch_bottom_y: updatePlayers.cpp:5706-5724. test D3 & (1<<D0).
    {
        int shift = d0 & 0x1F;
        int mask = 1 << shift;
        if ((d3 & mask) != 0)
        {
            // Out of pitch in this direction — clamp dest to current pos.
            int16_t sx = swosReadSignedWord(spriteAddr + SOffX);
            swosWriteWord(spriteAddr + SOffDestX, sx);
            int16_t sy = swosReadSignedWord(spriteAddr + SOffY);
            swosWriteWord(spriteAddr + SOffDestY, sy);
            return SWOS_PC_UPDATE_SPEED;
        }
    }

    // l_update_player_dest_x_y: updatePlayers.cpp:5733-5778.
    // Look up kDefaultDestinations[d0] (4 bytes per entry: dx word + dy word),
    // add to sprite.x/y, write to dest.
    {
        int byteOffset = (d0 & 0xFFFF) << 2;
        int16_t dx = swosReadSignedWord(ADDR_kDefaultDestinations + byteOffset);
        int16_t dy = swosReadSignedWord(ADDR_kDefaultDestinations + byteOffset + 2);
        int16_t sx = swosReadSignedWord(spriteAddr + SOffX);
        int16_t sy = swosReadSignedWord(spriteAddr + SOffY);
        int16_t newDx = (int16_t)(dx + sx);
        int16_t newDy = (int16_t)(dy + sy);
        // BUG FIX (2026-07-03, task #173 "cannot run/shoot bottom-right"):
        // the previous port applied a DEFENSIVE CLAMP here
        // (newDx→[81,590], newDy→[129,769]) that is NOT in the original asm
        // (updatePlayers.cpp:5733-5778 writes dest = pos + kDefaultDestinations
        // with no clamp). The clamp corrupted the movement ANGLE: a controlled
        // player in the right/lower half pressing a diagonal had its dest
        // pinned to the cushion corner (e.g. dest.x→590 while dest.y→769),
        // so CalculateDeltaXAndY resolved the vector to pure S or pure E
        // instead of the pressed diagonal — and for x∈{591,592} the clamp
        // pulled dest.x BELOW the current x, inverting deltaX (the player
        // ran LEFT while Down+Right was held). Verified: SE @(500,449) gave
        // dir'=4 (S), @(580,449) pure S, @(400,769) pure E.
        //
        // The clamp's stated rationale (off-ball sprites not re-entering
        // cseg_81793 every tick) does not apply: this path (RunControlledBranch)
        // only ever runs for `spriteAddr == team.controlledPlayer`
        // (UpdatePlayers.cs DispatchByPlayerState :3840 / keeper :793/912),
        // which IS re-entered every tick — exactly the condition the original
        // relies on. The cushion gate above (X>592 / Y>771 → dest=pos, stop)
        // already keeps the controlled player in bounds; the off-pitch dest
        // (pos ± 1000) is intentional and harmless because the NEXT tick's
        // gate stops the sprite at the boundary. Restored 1:1.
        swosWriteWord(spriteAddr + SOffDestX, newDx);
        swosWriteWord(spriteAddr + SOffDestY, newDy);
    }
    return SWOS_PC_UPDATE_SPEED;
}

// ===================================================================
// RunPassReceiptTrigger — updatePlayers.cpp:8180-8252
// ===================================================================
//
// The "pass arrived at a teammate" gate. Sits inside the
// `l_player_expecting_pass` branch (updatePlayers.cpp:7604) — NOT the
// `l_its_controlled_player` branch. The per-team-sprite dispatcher at
// updatePlayers.cpp:851-876 routes:
//
//     if (A1 == team.controlledPlayer)  → l_its_controlled_player
//     if (A1 == team.passToPlayerPtr)   → l_player_expecting_pass → ... → cseg_82D59
//
// These are MUTUALLY EXCLUSIVE branches. cseg_82D59 (the pass-receipt
// commit) is reached only by the second case, after several upstream
// guards including `team.passingToPlayer != 0` (line 7718) and a
// `passToPlayerPtr != 0` implicit guard (you cannot equal a null pointer
// and pass the line 875 compare).
//
// **Correction over the original port comment**: the previous comment
// claimed this block ran from `l_its_controlled_player`. That is wrong —
// the asm flow makes A1 == passToPlayerPtr the only way in. The pass
// receiver is a different sprite than the previously-controlled player.
//
// When all conditions fire, the asm commits:
//   team.controlledPlayer = team.passToPlayerPtr   (swap in the receiver)
//   team.passToPlayerPtr  = 0                      (consume the pending pass)
//   team.playerSwitchTimer = 25                    (debounce switch input)
//   team.passingBall      = 0                      (pass complete)
//   team.passingToPlayer  = 0
//   team.shooting         = 0                      (cancel shoot-armed state)
//   sprite.destX = sprite.x; sprite.destY = sprite.y  (snap receiver dest)
//   if ordinal==1: updateBallWithControllingGoalkeeper(sprite)
//   else:          updateControllingPlayer(sprite)
//
// Conditions inside cseg_82D59 itself (8182-8219):
//   1. team.ballLessEqual4 != 0            (ball is low — height <= 4 px)
//   2. ballSprite.speed >= 1536            (ball is moving fast — pass/shot)
//   3. team.plCloseToBall != 0 OR
//      team.plVeryCloseToBall != 0         (a teammate is near the ball)
//
// **Hardened call-site invariant (REGRESSION FIX 2026-06-01)**: the previous
// port called this from TickHumanControlled (the controlledPlayer branch)
// with sprite == team.controlledPlayer. That violated the asm's A1 identity
// (this should fire from the receiver branch). Combined with our half-
// ported ball-distance pipeline (Sprite.ballDistance never written → reads
// 0 → plVeryCloseToBall=1 for everyone), the trigger fired on tick 1 every
// match, executing `controlledPlayer = passToPlayerPtr (==0)` and zeroing
// both teams' controlledPlayer pointers, freezing all play. The guards
// below enforce the asm semantics directly:
//   - passToPlayerPtr != 0  (else swap zeroes controlledPlayer)
//   - sprite == passToPlayerPtr  (matches asm line 875 dispatch test)
//
// **Where the ball-sprite address comes from**: 8190 reads
// `g_memByte[329032]` which is `ballSprite.speed` (BALLSPR_BASE 0x4F800
// + OffSpeed 44 = 0x4F82C = 325676 decimal — not 329032 since swos-port
// and our port have different base addresses; we use the abstraction
// swosBallSpriteSpeed() which forwards to Memory).
//
// from updatePlayers.cpp:8180-8252
void swosRunPassReceiptTrigger(int spriteAddr, bool topTeam)
{
    int teamBase = swosTeamDataBase(topTeam);

    // REGRESSION FIX (2026-06-01): enforce the asm dispatch guard at
    // updatePlayers.cpp:865-876 — this branch only fires when the
    // iteration sprite IS the receiver. Without these checks, calling
    // this with the controlledPlayer sprite + null passToPlayerPtr
    // zeroes out the team's controlledPlayer and pins the ball.
    int passToPlayerPtrEarly = swosReadSignedDword(teamBase + TEAMDATA_OFF_PASS_TO_PLAYER_PTR);
    if (passToPlayerPtrEarly == 0) return;
    if (spriteAddr != passToPlayerPtrEarly) return;

    // updatePlayers.cpp:8182-8188 — ballLessEqual4 == 0 → bail.
    uint8_t ballLE4 = swosReadByte(teamBase + 64);  // OffBallLessEqual4
    if (ballLE4 == 0) return;

    // updatePlayers.cpp:8190-8201 — ballSprite.speed < 1536 → bail (cseg_82D82
    // path which then checks plVeryCloseToBall only). To match the asm
    // exactly: speed >= 1536 enables plCloseToBall as a valid trigger;
    // below 1536 only plVeryCloseToBall counts.
    int16_t ballSpeed = swosBallSpriteSpeed();

    bool plClose = swosReadByte(teamBase + TEAMDATA_OFF_PL_CLOSE_TO_BALL) != 0;
    bool plVeryClose = swosReadByte(teamBase + TEAMDATA_OFF_PL_VERY_CLOSE_TO_BALL) != 0;

    // updatePlayers.cpp:8200-8219 — gate dispatch:
    //   if ballSpeed >= 1536 AND plCloseToBall → l_passed_to_player_becomes_main
    //   else if plVeryCloseToBall              → l_passed_to_player_becomes_main
    //   else                                    → cseg_82EC2 (no trigger)
    bool trigger;
    if (ballSpeed >= 1536 && plClose)
    {
        trigger = true;
    }
    else if (plVeryClose)
    {
        trigger = true;
    }
    else
    {
        trigger = false;
    }

    if (!trigger) return;

    // l_passed_to_player_becomes_main — updatePlayers.cpp:8221-8229.
    // team.controlledPlayer = team.passToPlayerPtr; team.passToPlayerPtr = 0.
    int passToPlayerPtr = swosReadSignedDword(teamBase + TEAMDATA_OFF_PASS_TO_PLAYER_PTR);
    swosWriteDword(teamBase + TEAMDATA_OFF_CONTROLLED_PLAYER, passToPlayerPtr);
    swosWriteDword(teamBase + TEAMDATA_OFF_PASS_TO_PLAYER_PTR, 0);
    // playerSwitchTimer = 25 — debounce so the human can't switch again immediately.
    swosWriteWord(teamBase + TEAMDATA_OFF_PLAYER_SWITCH_TIMER, 25);
    // passingBall = 0; passingToPlayer = 0; shooting = 0.
    swosWriteWord(teamBase + TEAMDATA_OFF_PASSING_BALL, 0);
    swosWriteWord(teamBase + TEAMDATA_OFF_PASSING_TO_PLAYER, 0);
    swosWriteWord(teamBase + TEAMDATA_OFF_SHOOTING, 0);

    // updatePlayers.cpp:8230-8234 — esi=A1; sprite.destX = sprite.x.whole;
    // sprite.destY = sprite.y.whole. (The asm comments mislabel these as
    // TeamGeneralInfo fields but with esi=A1 they're Sprite.x/y high-words.)
    // Snaps the iteration sprite's destination to its current position so
    // the speed update doesn't drift it while the controlledPlayer swap
    // settles.
    int16_t spriteXw = swosReadSignedWord(spriteAddr + PLSPR_OFF_X + 2);
    int16_t spriteYw = swosReadSignedWord(spriteAddr + PLSPR_OFF_Y + 2);
    swosWriteWord(spriteAddr + PLSPR_OFF_DEST_X, spriteXw);
    swosWriteWord(spriteAddr + PLSPR_OFF_DEST_Y, spriteYw);

    // updatePlayers.cpp:8235-8252 — sprite.playerOrdinal == 1 (keeper)
    // → updateBallWithControllingGoalkeeper(A1); else → updateControllingPlayer(A1).
    int16_t ordinal = swosReadSignedWord(spriteAddr + PLSPR_OFF_PLAYER_ORDINAL);
    if (ordinal == 1)
    {
        // player.cpp:200 — pins ball at keeper's hand position.
        swosUpdateBallWithControllingGoalkeeper(spriteAddr);
    }
    else
    {
        // player.cpp:135 — pins ball one pixel in front of outfielder.
        swosUpdateControllingPlayer(spriteAddr);
    }

    // cseg_82E23 — updatePlayers.cpp:8254-8257 — clear pass-kick bookkeeping.
    swosWriteWord(teamBase + TEAMDATA_OFF_PASS_KICK_TIMER, 0);          // :8255
    swosWriteDword(teamBase + OffPassingKickingPlayer, 0);           // :8256
    swosWriteWord(teamBase + 116, 0);                                // :8257 field_74

    // updatePlayers.cpp:8259-8301 — BACK-PASS RULE. If the receiver is the
    // goalkeeper (playerOrdinal == 1):
    //   - ball last played by THIS team (A6 == lastTeamPlayed) AND
    //     playerHadBall == 0 (a deliberate pass, not a loose/contested
    //     ball) → keeper may NOT pick it up: goalkeeperPlaying = 1,
    //     goaliePlayingOrOut = 1, ballOutOfPlayOrKeeper = 1 — he controls
    //     the ball with his feet (updatePlayers.cpp:8285-8298).
    //   - otherwise (opponent played it last, or playerHadBall != 0) →
    //     cseg_82E92: GoalkeeperClaimedTheBall (updatePlayers.cpp:8300-8301).
    // NOTE: the gate reads lastTeamPlayed BEFORE the cseg_82E97 update below.
    if (ordinal == 1)
    {
        int lastTeamPlayed = swosReadSignedDword(ADDR_lastTeamPlayed);  // :8274
        int16_t playerHadBall = swosReadSignedWord(ADDR_playerHadBall);   // :8288
        if (teamBase == lastTeamPlayed && playerHadBall == 0)
        {
            // updatePlayers.cpp:8294-8297 — keeper plays with his feet.
            swosWriteWord(teamBase + TEAMDATA_OFF_GOALKEEPER_PLAYING, 1);        // :8295 (word +140)
            swosWriteByte(teamBase + TEAMDATA_OFF_GOALIE_PLAYING_OR_OUT, 1);       // :8296 (uint8_t +86)
            swosWriteByte(teamBase + TEAMDATA_OFF_BALL_OUT_OF_PLAY_OR_KEEPER, 1);    // :8297 (uint8_t +84)
        }
        else
        {
            // cseg_82E92 — updatePlayers.cpp:8300-8301.
            swosGoalkeeperClaimedTheBall(spriteAddr, teamBase == TEAMDATA_TOP_BASE);
        }
    }

    // cseg_82E97 — updatePlayers.cpp:8303-8310 — record possession.
    swosWriteDword(ADDR_lastTeamPlayed, teamBase);            // :8304-8305
    swosWriteDword(ADDR_lastPlayerPlayed, spriteAddr);        // :8306-8307
    swosWriteWord(ADDR_penalty, 0);                           // :8308
    swosWriteWord(ADDR_playerHadBall, 0);                     // :8309
}

// ===================================================================
// RunPassExpectingBranch — updatePlayers.cpp:7604-8311 (l_player_expecting_pass)
// ===================================================================
//
// The dispatcher branch the asm reaches when
//   spriteAddr == team.passToPlayerPtr  (updatePlayers.cpp:865-876).
//
// Source mapping (lines reference updatePlayers.cpp):
//   - l_player_expecting_pass entry        ......... 7604
//   - pitch-bounds test (player x in [81,590], y in [129,769]) 7605-7656
//     · out-of-pitch → clear passingToPlayer/passingBall, stop player (7658-7662)
//   - in-pitch CPU/human pass-direction update     7664-7891
//     · cpu team           → l_cpu_passing_to (7670-7672)
//     · long-pass / spin   → l_test_for_long_pass spin-offset table at
//                            kBallFriction (7674-7891). PORTED — see
//                            ApplyKBallFrictionOrFallback below + the
//                            kBallFriction table (verbatim copy of
//                            swos.asm:245568) earlier in this file.
//   - AI_Kick call for CPU team                    7892-7908
//   - gameStatePl == ST_GAME_IN_PROGRESS gate      7910-7922
//     · in-progress  → cseg_82C41 (8069-8311: keeper/tackle/receipt)
//     · stopped      → cseg_82AE5 (7924-8067: throw-in / pass-success direct commit)
//   - cseg_82D59 receiver-commit (8180-8252)        ── already in RunPassReceiptTrigger.
//   - cseg_82EC2 ball-chase fallback (8312-8430)    ── port here.
//
// Mechanical-port scope (this commit): pitch-bounds gate, the team.ballX/ballY
// refresh (CPU-team simple path + human long-pass spin via
// ApplyKBallFrictionOrFallback), the AI_Kick call, the in-progress dispatch
// (RunPassReceiptTrigger + cseg_82EC2 chase), and the game-stopped →
// pass-success commit (cseg_82AE5/AF6 → l_pass_success).
//
// What's STILL stubbed (cited inline):
//   - cseg_82CE1 tackle path inside cseg_82C41 (8101-8178) — playerBeginTackling
//     commit ported; gate logic + headerOrTackle/ballCanBeControlled writes
//     all live (see "cseg_82CE1 commit" inline). Opponent-team passing flag
//     wipe also ported.
//   - throw-in handoff at l_pass_success (8038-8067) — requires
//     SetThrowInPlayerDestinationCoordinates which is already ported.
//
// Hard rules: no floats, integer math only, cite source comments.
void swosRunPassExpectingBranch(int spriteAddr, bool topTeam)
{
    int teamBase = swosTeamDataBase(topTeam);
    // BALLSPR_BASE is implicitly the A2 register in swos-port; we don't
    // need to alias it here because the BallSprite static accessors index
    // it directly. Comment kept so future ports keep the asm-mapping clear.

    // updatePlayers.cpp:7605-7656 — pitch-bounds test on player's whole-pixel
    // (x, y). If x < 81 || x > 590 || y < 129 || y > 769 → out-of-pitch.
    int16_t pxWord = swosReadSignedWord(spriteAddr + SOffX);
    int16_t pyWord = swosReadSignedWord(spriteAddr + SOffY);
    bool outOfPitch = (pxWord < 81 || pxWord > 590 ||
                       pyWord < 129 || pyWord > 769);
    if (outOfPitch)
    {
        // updatePlayers.cpp:7658-7662 — clear pass flags, then l_stop_player.
        swosWriteWord(teamBase + TEAMDATA_OFF_PASSING_TO_PLAYER, 0);
        swosWriteWord(teamBase + TEAMDATA_OFF_PASSING_BALL, 0);
        // l_stop_player: snap destX/Y to current pos.
        swosWriteWord(spriteAddr + PLSPR_OFF_DEST_X, pxWord);
        swosWriteWord(spriteAddr + PLSPR_OFF_DEST_Y, pyWord);
        return;
    }

    // updatePlayers.cpp:7664-7891 — in-pitch ball-prediction update.
    // For CPU team (playerNumber == 0) → l_cpu_passing_to directly. For
    // human team the spin-offset table at kBallFriction is sampled to
    // lead the pass.
    // Mechanical port of updatePlayers.cpp:7670-7891 +
    // external/swos-port/swos/swos.asm:245568 (kBallFriction table data).
    applyKBallFrictionOrFallback(spriteAddr, teamBase);

    // updatePlayers.cpp:7892-7908 — l_cpu_passing_to: if team.playerNumber == 0
    // (CPU team) → AI_Kick(A1).
    int16_t playerNumber = swosReadSignedWord(teamBase + TEAMDATA_OFF_PLAYER_NUMBER);
    if (playerNumber == 0)
    {
        // from updatePlayers.cpp:19313 — AI_Kick. Helper takes the per-player
        // sprite + the team base. We call with this iteration's A1.
        requireAiKick(spriteAddr, teamBase);
    }

    // updatePlayers.cpp:7910-7922 — cseg_82AAF: gameStatePl != ST_GAME_IN_PROGRESS
    // routes to cseg_82C41 (the in-progress receipt chain). The asm test:
    //   cmp gameStatePl, 100 ; jz cseg_82C41
    // i.e. the in-progress path is the jz fall-through to cseg_82C41 starting
    // at 8069. The "stopped" path (cseg_82AE5+) is the jnz fall-through.
    int16_t gameStatePl = swosReadSignedWord(ADDR_gameStatePl);

    if (gameStatePl != 100)
    {
        // ----- Game-STOPPED path (cseg_82AE5..l_pass_success @ 7924-8067) ----
        // updatePlayers.cpp:7924-7935 — if lastTeamPlayedBeforeBreak != A6
        //   → l_update_player_speed_and_deltas (no commit). Stoppage came
        //     from the OTHER team's action; this team isn't the one resuming.
        int lastBeforeBreak = swosReadSignedDword(ADDR_lastTeamPlayedBeforeBreak);
        if (lastBeforeBreak != teamBase) return;

        // updatePlayers.cpp:7937-7972 — if gameState == ST_KEEPER_HOLDS_BALL (3)
        //   AND playerOrdinal != 1 (not a goalie) AND ballDistance != 0
        //   → cseg_82EC2 (chase path). Else fall through to l_pass_success.
        int16_t gs = swosReadSignedWord(ADDR_gameState);
        int16_t ordinalA1 = swosReadSignedWord(spriteAddr + SOffPlayerOrdinal);
        bool fallThroughToPassSuccess = false;
        if (gs == 3 && ordinalA1 != 1)
        {
            int bd = swosReadSignedDword(spriteAddr + SOffBallDistance);
            if (bd == 0)
                fallThroughToPassSuccess = true;
        }
        else
        {
            fallThroughToPassSuccess = true;
        }

        if (!fallThroughToPassSuccess)
        {
            // updatePlayers.cpp:cseg_82EC2 → fall through to chase. Implement
            // simple chase commit (8393-8417): dest = team.ballX/ballY.
            runChaseBall(spriteAddr, teamBase);
            return;
        }

        // ----- cseg_82AF6..l_pass_success @ 7974-8067 ---------------------
        // updatePlayers.cpp:7974-8003 — cameraDirection < 8 → l_pass_success
        // direct; else cameraDirection = sprite.direction.
        int16_t camDir = swosReadSignedWord(ADDR_cameraDirection);
        if (camDir >= 8)
        {
            int16_t spriteDir = swosReadSignedWord(spriteAddr + SOffDirection);
            swosWriteWord(ADDR_cameraDirection, spriteDir);
            // updatePlayers.cpp:7991-8002 — `add dseg_132804, 1`. Increments
            // a dead-statistical counter every time the pass-success branch
            // has to refresh cameraDirection from the receiver's sprite
            // direction (i.e. cameraDirection was out-of-range >= 8 at the
            // call site). Mirrors the dseg_132806 increment a few hundred
            // lines above (line 357 in this file) for the controlled-player
            // turn-flag override path.
            // Source: external/swos-port/src/game/updatePlayers/updatePlayers.cpp:7991-8002.
            int16_t cnt132804 = swosReadSignedWord(ADDR_dseg_132804);
            swosWriteWord(ADDR_dseg_132804, (int16_t)(cnt132804 + 1));
        }

        // l_pass_success @ 8004-8024 — commit pass receipt.
        int16_t camDirNow = swosReadSignedWord(ADDR_cameraDirection);
        swosWriteWord(spriteAddr + SOffDirection, camDirNow);
        int passToPtrNow = swosReadSignedDword(teamBase + TEAMDATA_OFF_PASS_TO_PLAYER_PTR);
        swosWriteDword(teamBase + TEAMDATA_OFF_CONTROLLED_PLAYER, passToPtrNow);
        swosWriteDword(teamBase + TEAMDATA_OFF_PASS_TO_PLAYER_PTR, 0);
        swosWriteWord(teamBase + TEAMDATA_OFF_PLAYER_SWITCH_TIMER, 25);
        swosWriteWord(teamBase + TEAMDATA_OFF_PASSING_BALL, 0);
        swosWriteWord(teamBase + TEAMDATA_OFF_PASSING_TO_PLAYER, 0);
        swosWriteWord(teamBase + TEAMDATA_OFF_SHOOTING, 0);
        // updatePlayers.cpp:8017 — A2 was ballSprite; `[esi+44]` is
        // ball.currentAllowedDirection-shaped — actually this writes to
        // ball.speed (offset +44 on BallSprite). The asm comment mislabels.
        // Setting ball.speed=0 here is consistent with "the ball is now
        // controlled by the receiver, momentum cancelled".
        swosWriteWord(BALLSPR_BASE + 44, 0);
        swosWriteDword(ADDR_lastTeamPlayed, teamBase);
        swosWriteDword(ADDR_lastPlayerPlayed, spriteAddr);
        swosWriteWord(ADDR_penalty, 0);
        swosWriteWord(ADDR_playerHadBall, 0);
        // updatePlayers.cpp:8024 — updatePlayerWithBall(A1).
        swosUpdatePlayerWithBall(spriteAddr);
        // updatePlayers.cpp:8026-8028 — reset pass timers.
        swosWriteWord(teamBase + TEAMDATA_OFF_PASS_KICK_TIMER, 0);
        swosWriteDword(teamBase + 104, 0);   // passingKickingPlayer
        swosWriteWord(teamBase + 116, 0);    // field_74
        // updatePlayers.cpp:8029-8067 — throw-in special-case for
        // gameState in [15..20]. SetPieces.SetThrowInPlayerDestinationCoordinates
        // would fire here. TODO from updatePlayers.cpp:8059 — throw-in
        // override during pass receipt is rare; not yet exercised by smoke.
        return;
    }

    // ----- Game-IN-PROGRESS path (cseg_82C41..@ 8069-8311) --------------
    //
    // updatePlayers.cpp:8069-8082 — playerOrdinal == 1 (goalie) → skip
    // the tackle branch and go straight to receipt at cseg_82D59.
    int16_t ordinalIp = swosReadSignedWord(spriteAddr + SOffPlayerOrdinal);
    bool goalieReceiving = (ordinalIp == 1);

    if (!goalieReceiving)
    {
        // updatePlayers.cpp:8084-8124 — non-goalie tackle pre-check.
        //   if fireThisFrame != 0 AND currentAllowedDirection >= 0
        //     AND plNotFarFromBall != 0
        //     AND (ballLessEqual4 != 0 OR ball4To8 != 0)
        //   then cseg_82CAB: compare ballDistance vs team.controlledPlayer's
        //     ballDistance; if A1 not closer → bail to cseg_82D59.
        //   Else cseg_82CE1 fires playerBeginTackling.
        //
        // cseg_82CE1 commit is ported below (8159-8178).
        uint8_t ftf = swosReadByte(teamBase + TEAMDATA_OFF_FIRE_THIS_FRAME);
        int16_t cad = swosReadSignedWord(teamBase + TEAMDATA_OFF_CURRENT_ALLOWED_DIRECTION);
        uint8_t pnf = swosReadByte(teamBase + 63);   // plNotFarFromBall
        uint8_t ble4 = swosReadByte(teamBase + 64);  // ballLessEqual4
        uint8_t b4to8 = swosReadByte(teamBase + 65); // ball4To8
        bool tackleGate = ftf != 0 && cad >= 0 && pnf != 0 &&
                          (ble4 != 0 || b4to8 != 0);
        if (tackleGate)
        {
            int controlled = swosReadSignedDword(teamBase + TEAMDATA_OFF_CONTROLLED_PLAYER);
            bool a1Closer = true;  // default: trigger if no controlled exists
            if (controlled != 0)
            {
                int ctrlDist = swosReadSignedDword(controlled + SOffBallDistance);
                int a1Dist = swosReadSignedDword(spriteAddr + SOffBallDistance);
                // cmp D1, eax; jb cseg_82D59 — A1 is closer iff a1Dist < ctrlDist (unsigned)
                a1Closer = (uint32_t)a1Dist < (uint32_t)ctrlDist;
            }
            if (a1Closer)
            {
                // updatePlayers.cpp:8159-8178 — cseg_82CE1 commit.
                // 8161 — team.headerOrTackle = 1 (locks input next frame).
                swosWriteWord(teamBase + TEAMDATA_OFF_HEADER_OR_TACKLE, 1);
                // 8166 — playerBeginTackling(D0=team.currentAllowedDirection).
                swosPlayerBeginTackling(spriteAddr, teamBase, cad);
                // 8172 — team.ballCanBeControlled = 0.
                swosWriteWord(teamBase + TEAMDATA_OFF_BALL_CAN_BE_CONTROLLED, 0);
                // 8173-8177 — opponent.passingToPlayer = 0; passingKickingPlayer = 0.
                int opponentTeamBase = swosReadSignedDword(teamBase + TEAMDATA_OFF_OPPONENTS_TEAM);
                if (opponentTeamBase != 0)
                {
                    swosWriteWord(opponentTeamBase + TEAMDATA_OFF_PASSING_TO_PLAYER, 0);
                    swosWriteDword(opponentTeamBase + TEAMDATA_OFF_PASSING_KICKING_PLAYER, 0);
                }
                // 8178 — jmp l_update_player_speed_and_deltas. Refresh speed/anim
                // and bail; we MUST NOT fall through to receipt path.
                swosUpdatePlayerSpeedAndFrameDelay(teamBase, spriteAddr);
                return;
            }
        }
    }

    // updatePlayers.cpp:8180-8252 (cseg_82D59) — receipt commit if the
    // ball is on the ground AND close enough. Already ported.
    // RunPassReceiptTrigger self-gates on spriteAddr == passToPlayerPtr.
    swosRunPassReceiptTrigger(spriteAddr, topTeam);

    // updatePlayers.cpp:8312-8634 (cseg_82EC2 → l_player_chase_ball →
    // l_player_still_moving tail) — if the receipt didn't fire, run the
    // full hold-position / chase / keeper-leash / crowd-stop chain.
    // Note: RunPassReceiptTrigger consumes passToPlayerPtr on success. If
    // it cleared it, the tail must not run. Detect by re-reading.
    int passPtrAfter = swosReadSignedDword(teamBase + TEAMDATA_OFF_PASS_TO_PLAYER_PTR);
    if (passPtrAfter == spriteAddr)
    {
        runPassChaseTail(spriteAddr, teamBase);
    }
}

// ===================================================================
// RunPassChaseTail — updatePlayers.cpp:8312-8634
// (cseg_82EC2 → l_its_a_pass → l_player_chase_ball →
//  l_player_still_moving → l_cancel_pass / cseg_8308D)
// ===================================================================
//
// Mechanically ported 2026-07-03 (task #154). The previous port jumped
// straight to the l_player_chase_ball dest write and skipped:
//   - the passingBall == 0 "hold position" branch (8322-8387): when the
//     team's controlledPlayer is closer to the ball than the receiver
//     (both within 3200), the RECEIVER's dest snaps to his OWN position
//     — the controlled player will take the ball instead;
//   - the keeper leash-zone cancel (8432-8561): a keeper chasing a pass
//     outside his box cancels the pass and stops;
//   - the goal-out crowd-zone stop for outfielders (8563-8634).
//
// The caller (router) runs UpdatePlayerSpeedAndFrameDelay after we
// return, which is the asm's l_update_player_speed_and_deltas join.
// l_stop_player is dest = own position, then the same join.
//
// from updatePlayers.cpp:8312.
static void runPassChaseTail(int spriteAddr, int teamBase)
{
    // cseg_82EC2 @ 8312-8320 — if passingBall != 0 → l_player_chase_ball.
    int16_t passingBall = swosReadSignedWord(teamBase + TEAMDATA_OFF_PASSING_BALL);
    if (passingBall != 0)
        goto l_player_chase_ball;

    {
        // 8322-8334 — A5 = team.controlledPlayer; if 0 → l_its_a_pass.
        int a5Controlled = swosReadSignedDword(teamBase + TEAMDATA_OFF_CONTROLLED_PLAYER);
        if (a5Controlled == 0)
            goto l_its_a_pass;

        // 8336-8348 — cmp [A5+Sprite.ballDistance], 3200; ja l_its_a_pass.
        int a5Dist = swosReadSignedDword(a5Controlled + SOffBallDistance);
        if ((uint32_t)a5Dist > 3200u)
            goto l_its_a_pass;

        // 8350-8364 — cmp A5.ballDistance, A1.ballDistance; ja l_its_a_pass
        // (controlled player farther than the receiver → it's a pass).
        int a1Dist = swosReadSignedDword(spriteAddr + SOffBallDistance);
        if ((uint32_t)a5Dist > (uint32_t)a1Dist)
            goto l_its_a_pass;

        // 8366-8377 — cmp [A1+Sprite.ballDistance], 3200; ja l_player_chase_ball.
        if ((uint32_t)a1Dist > 3200u)
            goto l_player_chase_ball;

        // 8379-8387 — hold: A1.destX/destY = A1's own x/y (the controlled
        // player is closer — HE will take the ball), then the speed join.
        int16_t holdX = swosReadSignedWord(spriteAddr + SOffX);
        int16_t holdY = swosReadSignedWord(spriteAddr + SOffY);
        swosWriteWord(spriteAddr + PLSPR_OFF_DEST_X, holdX);
        swosWriteWord(spriteAddr + PLSPR_OFF_DEST_Y, holdY);
        return;
    }

l_its_a_pass:
    // 8389-8391 — team.passingBall = 1.
    swosWriteWord(teamBase + TEAMDATA_OFF_PASSING_BALL, 1);

l_player_chase_ball:
    {
        // 8393-8401 — A1.destX = team.ballX; A1.destY = team.ballY.
        int16_t ballX = swosReadSignedWord(teamBase + TEAMDATA_OFF_BALL_X);
        int16_t ballY = swosReadSignedWord(teamBase + TEAMDATA_OFF_BALL_Y);
        swosWriteWord(spriteAddr + PLSPR_OFF_DEST_X, ballX);
        swosWriteWord(spriteAddr + PLSPR_OFF_DEST_Y, ballY);

        // 8402-8430 — D1 = A1.x.whole; D2 = A1.y.whole; if already at
        // (destX, destY) → speed join (done).
        int16_t d1 = swosReadSignedWord(spriteAddr + SOffX);
        int16_t d2 = swosReadSignedWord(spriteAddr + SOffY);
        int16_t destX = swosReadSignedWord(spriteAddr + PLSPR_OFF_DEST_X);
        if (d1 == destX)
        {
            int16_t destY = swosReadSignedWord(spriteAddr + PLSPR_OFF_DEST_Y);
            if (d2 == destY)
                return;
        }

        // l_player_still_moving @ 8432-8444 — cmp gameStatePl, 100;
        // jnz cseg_8308D.
        int16_t gameStatePl = swosReadSignedWord(ADDR_gameStatePl);
        if (gameStatePl != 100)
            goto cseg_8308D_entry;

        // 8446-8458 — cmp [A1+Sprite.playerOrdinal], 1; jnz cseg_8308D.
        int16_t ordinal = swosReadSignedWord(spriteAddr + SOffPlayerOrdinal);
        if (ordinal != 1)
            goto cseg_8308D_entry;

        // 8460-8467 — cmp team.goalkeeperPlaying, 0; jnz cseg_8308D.
        int16_t goalkeeperPlaying = swosReadSignedWord(teamBase + TEAMDATA_OFF_GOALKEEPER_PLAYING);
        if (goalkeeperPlaying != 0)
            goto cseg_8308D_entry;

        // 8469-8479 — cmp A6, offset bottomTeamData; jz cseg_8303E.
        if (teamBase == TEAMDATA_BOTTOM_BASE)
            goto cseg_8303E;

        // ---- TOP-team keeper leash (goal at the top) -------------------
        // 8481-8491 — cmp D2, 206; jg l_cancel_pass.
        if (d2 > 206)
            goto l_cancel_pass;
        // 8493-8503 — cmp D1, 203; jl l_cancel_pass.
        if (d1 < 203)
            goto l_cancel_pass;
        // 8505-8515 — cmp D1, 468; jg l_cancel_pass.
        if (d1 > 468)
            goto l_cancel_pass;
        // 8517 — jmp l_update_player_speed_and_deltas.
        return;

    cseg_8303E:
        // ---- BOTTOM-team keeper leash (goal at the bottom) -------------
        // 8519-8530 — cmp D2, 692; jl l_cancel_pass.
        if (d2 < 692)
            goto l_cancel_pass;
        // 8532-8542 — cmp D1, 203; jl l_cancel_pass.
        if (d1 < 203)
            goto l_cancel_pass;
        // 8544-8554 — cmp D1, 468; jle l_update_player_speed_and_deltas.
        if (d1 <= 468)
            return;
        // fall through

    l_cancel_pass:
        // 8556-8561 — clear passToPlayerPtr + passingBall + passingToPlayer,
        // then l_stop_player.
        swosWriteDword(teamBase + TEAMDATA_OFF_PASS_TO_PLAYER_PTR, 0);
        swosWriteWord(teamBase + TEAMDATA_OFF_PASSING_BALL, 0);
        swosWriteWord(teamBase + TEAMDATA_OFF_PASSING_TO_PLAYER, 0);
        goto l_stop_player;

    cseg_8308D_entry:
        // cseg_8308D @ 8563-8570 — if goalOut == 0 → speed join.
        int16_t goalOut = swosReadSignedWord(ADDR_goalOut);
        if (goalOut == 0)
            return;

        // 8572-8584 — keepers (ordinal == 1) skip the crowd-zone stop.
        int16_t ord2 = swosReadSignedWord(spriteAddr + SOffPlayerOrdinal);
        if (ord2 == 1)
            return;

        // 8586-8608 — cmp D1, 183; jl done. cmp D1, 488; jg done.
        if (d1 < 183)
            return;
        if (d1 > 488)
            return;

        // 8610-8632 — cmp D2, 226; jle l_stop_player.
        //             cmp D2, 672; jge l_stop_player. else done.
        if (d2 <= 226)
            goto l_stop_player;
        if (d2 >= 672)
            goto l_stop_player;
        return;

    l_stop_player:
        // l_stop_player — dest = own position (same commit as the
        // out-of-pitch branch above), then the speed join in the caller.
        swosWriteWord(spriteAddr + PLSPR_OFF_DEST_X, d1);
        swosWriteWord(spriteAddr + PLSPR_OFF_DEST_Y, d2);
    }
}

// updatePlayers.cpp:8393-8431 — l_player_chase_ball.
// sprite.destX = team.ballX; sprite.destY = team.ballY; if sprite is
// already at (destX,destY) the speed update is a no-op. We mirror the
// simple assignment; the chase loop in 8432+ handles cancel-pass /
// goalkeeper override which we don't need for the mechanical port.
//
// from updatePlayers.cpp:8393.
static void runChaseBall(int spriteAddr, int teamBase)
{
    int16_t ballX = swosReadSignedWord(teamBase + TEAMDATA_OFF_BALL_X);
    int16_t ballY = swosReadSignedWord(teamBase + TEAMDATA_OFF_BALL_Y);
    // DEFENSIVE CLAMP — team.ballX/Y can briefly be off-pitch when a kick
    // sends the ball over the touchline before the OOB handler reins it
    // in. Stomping that onto a chaser's dest would let the chaser drift
    // beyond the cushion. Same band as setPlayerWithNoBallDestination
    // (updatePlayers.cpp:15608-15666).
    if (ballX <  81) ballX =  81;
    if (ballX > 590) ballX = 590;
    if (ballY < 129) ballY = 129;
    if (ballY > 769) ballY = 769;
    swosWriteWord(spriteAddr + SOffDestX, ballX);
    swosWriteWord(spriteAddr + SOffDestY, ballY);
}

// ===================================================================
// All callees now route to real ports:
//   AI_SetControlsDirection      → AiBrain.SetControlsDirection
//   UpdatePlayerWithBall         → PlayerActions.UpdatePlayerWithBall
//   AttemptStaticHeader          → PlayerHeader.AttemptStaticHeader
//   CalculateIfPlayerWinsBall    → PlayerActions.CalculateIfPlayerWinsBall
//   DoPass                       → PlayerActions.DoPass
//   PlayerKickingBall            → PlayerActions.PlayerKickingBall
//   PlayerAttemptingJumpHeader   → PlayerHeader.PlayerAttemptingJumpHeader
//   PlayerBeginTackling          → PlayerTackle.PlayerBeginTackling
//   UpdateControllingPlayer      → PlayerActions.UpdateControllingPlayer
//     (fired from RunPassReceiptTrigger above)
//
// Note: PlayerTackle.PlayerTacklingTestFoul is the foul-check that runs
// AFTER a tackle hits (called from UpdatePlayers kTackling case at
// UpdatePlayers.cs:777). PlayerTackle.PlayerBeginTackling is the entry
// that transitions a player INTO the kTackling state.
// ===================================================================

// kBallFriction spin-offset table. Mechanical port of
//   external/swos-port/swos/swos.asm:245568
// 32 pairs (dx, dy) indexed by ((ballFullDir + spinSign + 4) & 0xFF) >> 3.
// Values are pixel offsets (scaled by 1000-unit step). Used to lead the
// pass target when the ball is moving and the carrier wants to "spin" it.
// BUG FIX (2026-07-03, task #154): the previous transcription of this table
// dropped the (1000, 1000) pair at slot 12 (the asm source wraps mid-pair
// across `dw` lines at swos.asm:245570-245571), leaving 63 shorts instead
// of 64 and shifting every pair from slot 12 onward — slot 31 read past the
// end of the array. Re-transcribed pair-by-pair from swos.asm:245568-245573.
static const int16_t kBallFriction[] =
{
    // slots 0..7
        0, -1000,   199, -1000,   414, -1000,   668, -1000,
     1000, -1000,  1000,  -668,  1000,  -414,  1000,  -199,
    // slots 8..15
     1000,     0,  1000,   199,  1000,   414,  1000,   668,
     1000,  1000,   668,  1000,   414,  1000,   199,  1000,
    // slots 16..23
        0,  1000,  -199,  1000,  -414,  1000,  -668,  1000,
    -1000,  1000, -1000,   668, -1000,   414, -1000,   199,
    // slots 24..31
    -1000,     0, -1000,  -199, -1000,  -414, -1000,  -668,
    -1000, -1000,  -668, -1000,  -414, -1000,  -199, -1000,
};

// Mechanical port of updatePlayers.cpp:7664-7891 — long-pass spin update.
// Drives the team.ballX/ballY lead targeting used by the pass-receipt
// chain.
//
// BUG FIX (2026-07-03, task #154 "receiver veers off mid-pass"): the
// previous version of this function diverged from the asm in four ways
// that combined into the reported symptom:
//   1. It was MISSING the longPass/leftSpin/rightSpin gate at
//      updatePlayers.cpp:7674-7696, so the fullDirection "not turned
//      enough" check ran for EVERY human pass. A receiver running toward
//      an incoming ball faces roughly opposite the ball's direction
//      (|delta| ≈ 128 > 64), so passingToPlayer/passingBall were cleared
//      on effectively every plain pass. With passingToPlayer == 0,
//      InputControls.UpdatePlayerBeingPassedTo (swos.asm:101066-101073
//      gate) re-elects passToPlayerPtr every tick to the sprite CLOSEST
//      to the ball — early in the flight that is someone near the passer,
//      so the intended receiver was un-designated (dest snapped to own
//      pos, then routed to the AI positioning tail → walked back to
//      formation), and only re-elected once the ball got close to him
//      ("remembers and comes back"). In the original, a plain pass
//      (no longPass/spin) never reaches the fullDirection check at all.
//   2. Every fallback path wrote team.ballX/ballY = live ball position.
//      The asm writes NOTHING on those paths (l_cpu_passing_to has no
//      ballX/Y store — the per-tick mirror in UpdatePlayerBeingPassedTo
//      at swos.asm:101049-101057 is the only refresher).
//   3. l_ball_got_no_direction (7794-7803) writes ballX/Y from the
//      RECEIVER's own x/y (esi = A1), not the ball's — i.e. "stand where
//      you are, the pass is coming straight at you".
//   4. The spin/lead path (7862-7890) bases the target on the RECEIVER's
//      position (esi = A1) + kBallFriction entry, not the ball's.
//
// Branch map (lines reference updatePlayers.cpp):
//   7664-7672: CPU team (playerNumber == 0) → l_cpu_passing_to (no write).
//   7674-7696: longPass == 0 && leftSpin == 0 && rightSpin == 0
//              → l_cpu_passing_to (no write).
//   7698-7710: ballSprite.speed < 512 (unsigned) → l_cpu_passing_to.
//   7712-7719: passingToPlayer == 0 → l_cpu_passing_to.
//   7721-7727: ballSprite.direction < 0 → l_ball_got_no_direction.
//   7729-7761: D0 = ball.fullDirection - receiver.fullDirection (int8);
//              |D0| > 64 → l_player_not_turned_enough_toward_ball:
//              clear passingToPlayer + passingBall, → l_cpu_passing_to
//              (NO ballX/Y write).
//   7769-7792: -4 <= D0 <= 4 → l_ball_got_no_direction:
//              team.ballX/Y = receiver.x/y.
//   7805-7890: spin lead: D1 = longPass ? 224 : 192 (negated if D0 < 0);
//              slot = ((ball.fullDir + D1 + 4) & 0xFF) >> 3;
//              team.ballX = receiver.x + kBallFriction[slot].dx;
//              team.ballY = receiver.y + kBallFriction[slot].dy.
// Source:
//   external/swos-port/src/game/updatePlayers/updatePlayers.cpp:7664-7891
//   external/swos-port/swos/swos.asm:245568 (kBallFriction)
static void applyKBallFrictionOrFallback(int spriteAddr, int teamBase)
{
    // updatePlayers.cpp:7664-7672 — CPU team: → l_cpu_passing_to, no write.
    int16_t playerNumber = swosReadSignedWord(teamBase + TEAMDATA_OFF_PLAYER_NUMBER);
    if (playerNumber == 0)
        return;

    // updatePlayers.cpp:7674-7696 — plain pass gate: only longPass OR
    // leftSpin OR rightSpin enters the prediction block; otherwise
    // → l_cpu_passing_to (no write, no flag clearing).
    int longPass = swosReadSignedDword(teamBase + TEAMDATA_OFF_LONG_PASS);
    if (longPass == 0)
    {
        int16_t leftSpin = swosReadSignedWord(teamBase + TEAMDATA_OFF_LEFT_SPIN);
        if (leftSpin == 0)
        {
            int16_t rightSpin = swosReadSignedWord(teamBase + TEAMDATA_OFF_RIGHT_SPIN);
            if (rightSpin == 0)
                return;
        }
    }

    // updatePlayers.cpp:7698-7710 — `cmp ballSprite.speed, 512 / jb @@cpu_passing_to`.
    // Unsigned compare: under 512 → no write.
    int ballSpeed = swosBallSpriteSpeed();
    if ((uint16_t)ballSpeed < 512)
        return;

    // updatePlayers.cpp:7712-7719 — `cmp team.passingToPlayer, 0 / jz @@cpu_passing_to`.
    int16_t passingToPlayer = swosReadSignedWord(teamBase + TEAMDATA_OFF_PASSING_TO_PLAYER);
    if (passingToPlayer == 0)
        return;

    // The receiver's whole-pixel position — the base for every target
    // write below (asm: esi = A1 at 7795-7802 and 7862-7890).
    int16_t recvX = swosReadSignedWord(spriteAddr + PLSPR_OFF_X + 2);
    int16_t recvY = swosReadSignedWord(spriteAddr + PLSPR_OFF_Y + 2);

    // updatePlayers.cpp:7721-7727 — `mov ax, ballSprite.direction / js l_ball_got_no_direction`.
    // direction is the QUANTISED 0..7 uint8_t; the `js` checks bit 15 of the
    // word — i.e. direction == -1 (no direction).
    int16_t ballDir = swosBallSpriteDirection();
    int16_t ballFullDir = swosBallSpriteFullDirection();
    if (ballDir < 0)
        goto l_ball_got_no_direction;

    {
        // updatePlayers.cpp:7729-7738 — D0 = ball.fullDirection - player.fullDirection
        // (signed 8-bit subtract). Both are 0..255 angles.
        int16_t playerFullDir = swosReadSignedWord(spriteAddr + PLSPR_OFF_FULL_DIRECTION);
        int8_t d0 = (int8_t)((uint8_t)(ballFullDir & 0xFF) - (uint8_t)(playerFullDir & 0xFF));

        // updatePlayers.cpp:7740-7761 — `cmp D0, 64 / jg` and `cmp D0, -64 / jl`
        // → l_player_not_turned_enough_toward_ball.
        if (d0 > 64 || d0 < -64)
        {
            // updatePlayers.cpp:7763-7767 — clear passingToPlayer +
            // passingBall, then `jmp @@cpu_passing_to` — NO ballX/Y write.
            swosWriteWord(teamBase + TEAMDATA_OFF_PASSING_TO_PLAYER, 0);
            swosWriteWord(teamBase + TEAMDATA_OFF_PASSING_BALL, 0);
            return;
        }

        // updatePlayers.cpp:7769-7792 — cseg_82952: `cmp D0, 4 / jg spin`
        // and `cmp D0, -4 / jl spin`; fall-through (|D0| <= 4)
        // → l_ball_got_no_direction.
        if (d0 <= 4 && d0 >= -4)
            goto l_ball_got_no_direction;

        // updatePlayers.cpp:7805-7816 — D1 selector: 192 default, 224 when
        // longPass (dword field, zero/non-zero gate).
        int8_t d1 = (int8_t)(longPass != 0 ? 224 : 192);

        // updatePlayers.cpp:7818-7827 — cseg_829AC:
        //   mov al, uint8_t ptr D0 / or al, al / jl cseg_829BB / neg uint8_t ptr D1
        // The `jl` SKIPS the negation when D0 is NEGATIVE — i.e. D1 is
        // negated when D0 >= 0.
        // BUG FIX (2026-07-03, task #172 "receiver runs away from spun
        // pass"): this condition was previously `d0 < 0` — inverted vs the
        // asm — so the perpendicular lead offset pointed to the WRONG side
        // of the ball's travel line (e.g. ball east, receiver north of the
        // line, D0 > 0: original leads at ballDir+64 = south = intercept;
        // inverted led at ballDir-64 = north = away from the ball).
        if (d0 >= 0)
            d1 = (int8_t)(-d1);

        // updatePlayers.cpp:7829-7861 — slot = ((ball.fullDir + D1 + 4) & 0xFF) >> 3
        // (the asm's extra `shl 2` is the uint8_t stride for dw pairs; our
        // managed array steps in shorts, 2 per slot).
        int angle = (uint8_t)((ballFullDir & 0xFF) + d1 + 4);
        int idx = (angle >> 3) & 0x1F;  // 0..31

        // updatePlayers.cpp:7862-7890 — team.ballX = receiver.x + table[slot].dx;
        //                               team.ballY = receiver.y + table[slot].dy.
        int16_t dx = kBallFriction[idx * 2];
        int16_t dy = kBallFriction[idx * 2 + 1];
        swosWriteWord(teamBase + TEAMDATA_OFF_BALL_X, (int16_t)(recvX + dx));
        swosWriteWord(teamBase + TEAMDATA_OFF_BALL_Y, (int16_t)(recvY + dy));
        return;
    }

l_ball_got_no_direction:
    // updatePlayers.cpp:7794-7803 — team.ballX/Y = RECEIVER's own x/y
    // (esi = A1): the pass is on target, hold position and wait for it.
    swosWriteWord(teamBase + TEAMDATA_OFF_BALL_X, recvX);
    swosWriteWord(teamBase + TEAMDATA_OFF_BALL_Y, recvY);
}
